# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define h = Character("Humanity")
define politician = Character("Politician")
define one_of_billions = Character("One of Billions within Humanity")
define a_child_among_billions = Character("A Child Among Billions")
define a_believer = Character("A Believer Among Billions")
define a_preacher = Character("A Preacher Among Billions")
define astronomer = Character("An Astronomer Among Billions")
image bg earth_view_orbit = "P1C4/bg P1C4_view_of_Earth_from_orbit.png"
image bg earth_view_2 = "P1C4/bg P1C4_view_of_Earth_from_orbit_2.png"

label P1C4:
    show screen centeredbox("{size=+10}Chapter 4: A Way Out?{/size}")
    pause
    hide screen centeredbox
    show screen centeredbox("Note: As the main character is the assimilation of billions of human beings, it uses the words \"I\" and \"we\" interchangeably based on how it feels.")
    pause
    hide screen centeredbox

    scene bg earth_view_orbit

    politician "Do you know what year it is, or how long it has been since we have been trapped in this form?"
    one_of_billions "I lost count after about twelve"
    one_of_billions "I don’t think we age anymore."
    one_of_billions "Does it still matter?"
    h "Perhaps, I did still age."
    h "Perhaps I did not."
    h "There was no mirror."
    h "I could not raise my hands to my eyes or scream in the darkness."
    h "All I had were the orbits of the planets to tell me of the passage of time."
    h "We stayed fixed in one place, never moving, never interacting with anything within the solar system."
    h "We did not revolve around a large body, and only rotated approximately a degree every five minutes or so."
    h "Each year, we were given a close glimpse of the planet we once called home as it crossed our field of vision and then left."
    h "The first day, all the lights could still be seen on the earth."
    h "Afterwards, it was complete darkness."
    h "If I knew the predicament I was in rather than simply denying it, perhaps we would have savored the sight I saw on that first day even more."
    h "Rather than wallow in disorientation, we could have lived in the moment, assuming that I am still living."
    a_child_among_billions "Is this hell?"
    a_believer "It must be"
    a_believer "Even though we were forgiven for our sins, that didn't absolve us of our responsibilities as God's creations."
    a_believer "We have sinned and this is our punishment."
    a_preacher "Then who among us is most guilty?"
    h "A preacher's voice boomed across the emptiness of space from within me."
    a_preacher "Who is the one who has doomed us to this fate?"
    scene bg earth_view_2
    h "An interesting question."
    h "Was it the soldiers that fought the wars?"
    h "No."
    h "They were the greatest patriots."
    h "Was it the serial killers and mass murderers?"
    h "Perhaps, but they were a misguided product of their society."
    h "Who among me has created those parts of me?"
    h "Mediocre parents, abusive teachers, gun manufacturers, war hungry leaders, human traffickers, drug dealers, exploitative employers, dishonest journalists, pedophiles, rapists, the authority, the elite, the vagrants."
    h "All are part of me."
    h "All of them are me."
    h "I am as guilty as I am innocent."
    h "The generation before us made us flaws and imperfections, and left us here to suffer while they could enjoy death and freedom from this form of existence."
    h "Who do I burn at the stake now that we’re here like this?"
    h "Where is the pike for me to parade the heads of the villains who created this outcome?"
    h "And who among me is most befitting of the role of executioner?"
    h "I doubt there is even one among me that is without sin, who can cast the first stone, raise the ax, and load the bullets for the firing squad."
    h "I hate so much of myself for conflicting reasons."
    h "All the imperfect and flawed individuals, no matter how high of an office or low of a position they held were me."
    h "I hate the capitalists and I also hate the communists."
    h "I hate those who are citizens of the United States, and I also hate those who are citizens of Russia."
    h "I hate one side of me, and the side I hate despises the others."
    h "The ones on the other side are the ones responsible."
    h "They are the ones who should be punished."
    h "Don't lump them in with us."
    h "Or else we, all sides, all of me, will never find peace."
    h "I am the one pursued by the mob and I am the mob itself."
    h "Indeed, we have seen moments like this before—moments where we were placed on trial, judged for our crimes, regardless of guilt or innocence."
    h "The times I have been framed for a murder and separated from my children by the justice system."
    h "I stood there in a publicized court at the mercy of a judge and jury who knew nothing about me or what I had at stake and a disinterested public defender who was overburdened by the number of cases he needed to handle."
    h "Even before the trial started, I was met with vitriol and disgust. I learned then that in the court of public opinion, I was guilty until proven innocent."
    h "Everyone wanted something from me except the things I wanted."
    h "The zealous prosecutor wanted the death penalty."
    h "He and his team fought tooth and nail ensure that I get nothing, not even a morsel."
    h "He fought for death, but I was given life in prison instead as though it was supposed to be some form of mercy."
    h "The reasoning was that the severity of the crime notwithstanding, my financial situation and my gender did not warrant an execution."
    h "I was privileged enough to avoid death, but lacking enough privilege to avoid a life of intense suffering."
    h "The humiliation I felt at that point was unbearable, as though I truly wished to repent for a crime I did not commit."
    h "It was then that I realized that justice was fickle, and that truth, regardless of its value, only had meaning when it was revealed."
    h "In the days following the trial, I was immediately sent to a high security prison without even given the chance to see my family or protest the decision in any way."
    h "My identity was overtaken by my sentence."
    h "My education, my past accomplishments, all the good I have done was replaced by what a court incorrectly decided I was."
    h "Whether it be through boredom, an unwarranted enmity, or self-hatred, those around me turned against me."
    h "However, those moments were in the minority as I spent the majority of my time in a cell, watching an unchanging scenery from behind a set of bars."
    h "Trapped ‘til death do us part."
    astronomer "There’s no need to count the years"
    astronomer "The stars can tell us exactly how long it has been."
    h "Astronomical dating."
    h "It is a possibility."
    h "But I am merely an accumulation of all living humans in the form of a single individual."
    h "I have all my senses, but I do not appear to have a human body."
    h "My vision is that of a human’s."
    h "My hearing, if it worked in this empty vacuum of space, is most likely the same."
    h "There is no air here, but if I could smell, what scent would I recognize?"
    h "Taste? Taste is not even worth mentioning."
    h "If I could speak, even if someone could hear me, what could I say?"
    h "The stars in the distance were dim and did not twinkle."
    h "There was no telescope here."
    h "No technology or tools."
    h "Nothing can be made, and nothing can be used except for my mind."
    h "Physical autonomy was a thing of the past."
    h "Sometimes, I would catch a comet or planetary bodies in the form of colored dots when the sun was behind me."
    h "It was a rough guess, but we think that it has been almost a century."
    h "A century of nothing."
    h "I have eyes but I cannot close them."
    h "I long for sleep, but have no need to."
    h "And with the absence of sleep is also the absence of dreams which was one of my primary escapes before I became… this."
    h "Now, the only escapes are the memories of billions and my imagination which serves not only to occasionally free me, but also tortures me incessantly as it did when I walked the earth as many instead of one."
    h "My sight acts not only as a reminder of the state we are in, but also as the source of infinite boredom as I spin and spin."
    h "The days blend into weeks, which become years and decades."
    h "I have these memories of lives with gaps, empty spaces, and blanks."
    h "Lives that ended in accidents and injuries, but still lived to become a part of me."
    h "From the outside, I can see nurses and doctors act as witness to the events that occurred during these blanks."
    h "Wires everywhere leading from bodies to monitors."
    h "Intravenous catheters to deliver nutrients to my emaciated body while I lay there on a hospital bed unaware of the happenings of the world."
    h "Maybe it was for the best."
    h "If I could see myself, injured, burnt, scarred, and unconscious, I would have asked to pull the plug."
    h "Now, I see myself wishing that there was a plug."
    h "Yes, I can see the entirety of existence for what it is, but at what cost?"
    h "Even if I did recover and woke up, there was no normal life waiting for me at the end of all the time that had passed."
    h "To see myself, old and decrepit, with my youth robbed from me."
    h "To see the world move on without me and leave me behind. How different would that be from this?"
    h "Those among me that were unconscious were fortunate."
    h "When I was conscious, but unable to communicate, it was as though reality was ridiculing me."
    h "Telling me that it placed me on that hospital bed to allow me to see my own funeral as my family and loved ones fought over whether I lived or died."
    h "I remember wishing that someone, anyone, would help me."
    h "That if they could not save me, they would reassure me."
    h "Now, if anyone is to save me, they would be light years away, maybe on another planet."
    h "They could be in another time in the far future, waiting to evolve into a form that had the intelligence and capabilities to take to the stars."
    h "Someone please…"
    h "I’m not a princess in a fairytale."
    h "The only one who can save me is myself if such a thing is possible."
    h "But we can’t save ourselves. "
    h "We don't know how."
    h "My eyes cannot weep."
    h "If I had a mouth, my sobs would be lost in this blackness."
    h "If I had a heart, its aches would not even register."
    h "Nothing can save me from this misery that I cannot even feel."
    h "No longer do I operate in the world of the living. I am now peer to the planets, stars and galaxies, waiting for salvation on a cosmological timescale extending almost infinitely into an unknown future."
    h "This is our reality now, whether I like it or not."
    h "Privacy, identity, a sense of self."
    h "All are gone now."
    h "There is only me, Humanity, left to shoulder the future burdens of the race that came before me regardless of whether I am able to do so or not."
    # This ends the game.
    jump P1C5