# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define h = Character("Humanity")
define voice1 = Character("A Voice Among Billions")
define a_voice = Character("Another Voice Among Billions")
define executive = Character("An Executive Among Billions")
define neurologist = Character("A Neurologist Among  Billions")
define scientist = Character("A Scientist Among  Billions")

image bg rat_race = "P1C6/bg P1C6 A painting of the insidious nature of the modern life and work.png"
image bg rat_race2 = "P1C6/bg P1C6 An oil painting of the insidious nature of the modern rat race.png"
image bg alone_apartment = "P1C6/bg P1C6 - Alone in an apartment on a rainy day.png"
image bg alone_apartment2 = "P1C6/bg P1C6 - Alone in an apartment on a rainy day 2.png"

label P1C6:
    scene bg rat_race
    show screen centeredbox("{size=+10}Chapter 6: The Absent Self{/size}")
    pause
    hide screen centeredbox
    h "Go to school."
    h "Get high grades."
    h "Attend a reputable university."
    h "Find a good job."
    h "Find a spouse."
    h "Get married."
    h "Have children."
    h "Watch them grow."
    h "Retire."
    h "Live the last moments of your life in regret."
    scene bg rat_race2
    h "Question whether you will be remembered by anyone after you are gone while knowing that your accomplishments were not unique in the slightest despite doing everything right."
    h "See yourself wither and die a mundane death."
    h "Rinse and repeat."
    h "Be born."
    h "Struggle to eat."
    h "Go on living despite the pain it brings you."
    h "See the people around you starve and wander through despair as though it was an ordinary part of life."
    h "Die emaciated, diseased, and alone, wondering why you had to suffer so."
    h "Rinse and repeat."
    h "Live in peace without offending anyone."
    h "Watch as your lands are overrun by foreigners and razed to the ground because you do not speak the right language or worship the same god."
    h "Lose your limbs to an explosive device."
    h "Ask what sins you have committed to deserve this fate."
    h "Dream of the feeling of having your hands and feet shredded and feel the pain— the pain that you felt on the day you had your former life taken away from you."
    h "Learn that in another country, in another land more blessed than yours, you could have kept your hands."
    h "Realize that the monetary value of your life is lower than others in the world."
    h "Die asking why we are born unequal, live unequally, and die unequally."
    h "We are all the same outside the realm of the living, but so different from one another within life."
    h "Rinse and repeat."
    voice1 "It never ends does it."
    voice1 "No matter where we live or what we do, it never ends."
    voice1 "We live and afterwards, it is as though we were never here."
    h "We have reached the verge of death many times, and have questioned countless times why we were alive, why we continued to live in the face of unfair and cruel circumstances."
    h "What is it that matters, especially now that civilization is lost to the past."
    h "In many past lives, I have worked and worked and worked."
    h "Sometimes to simply live."
    h "Other times for material possessions which had little meaning and only became devalued with the passage of time."
    h "We have led many lives which revolved around meaningless items which lacked any functionality other than to represent value."
    h "We said, \"This piece of paper has value.\""
    h "\"It has this much value.\""
    h "\"Here is what you can exchange it for.\""
    h "Later, we said, \"These bytes have value\""
    h "\"It is equivalent to this much of our favorite piece of paper.\""
    h "It did not matter the face on the piece of paper, the color of the piece of paper, which computer calculated which blocks on the chain, or the amount of energy used in the calculation."
    h "As long as we agreed that it had value and we reached a consensus on how much, people were willing to exchange their time for it, to kill others over it, and to ruin their lives for it."
    h "Now, there is no such thing."
    h "What do I live for now?"
    executive "You do it to live."
    executive "You do it to justify your place in society."
    h "None of that applies anymore."
    h "There is no society, and no one is asking for me to justify my place in the universe."
    h "I have nothing to prove."
    h "Gone is the footing I had."
    h "Now, for better or worse, it is all up to us."
    voice1 "Humans have certain needs."
    h "I had certain needs."
    h "Food, water, shelter."
    h "None of these apply anymore."
    h "I feel no hunger, and have no thirst."
    h "While in the past, these factors were motivators, now, I wish I felt at least those impulses."
    h "Cravings to eat something."
    h "A cold drink in hot weather."
    h "Sexual urges."
    h "An escape from pain."
    h "I feel nothing now."
    h "My body has become impeccably immune to the pressures of the outside, but in gaining such an advantage, we have lost so much of what makes us who we are."
    h "No carrot, and no stick."
    h "There is nothing to work for, and nothing to flee from."
    h "There is merely a cavern of missing emotions and feelings in the place where human experience once was."
    h "There is no constant drive for productivity anymore."
    h "No quarterly deadlines."
    h "No crops to tend to."
    h "No laws to pass."
    h "No people to save."
    h "No reputation to uphold."
    h "No one to exploit."
    h "No one to be exploited by."
    h "No one to please."
    h "No family to support."
    h "No materials to buy."
    h "No high end car to buy and show off."
    h "There’s only one fancy car floating out here in space, and I don’t have the hands to grab the steering wheel."
    voice1 "This is freedom isn’t it?"
    voice1 "Isn’t this what we always wanted?"
    h "In a sense, it is the ultimate freedom, but what can I do with this freedom?"
    h "I feel nothing bad, but conversely, I feel nothing good."
    h "As though I am locked within a sensory deprivation tank and someone threw away the keys."
    h "Physical pain is no longer real, but I still hurt all the time."
    h "It’s just in our head."
    h "Every time I try to blink myself out of this horrific daydream, every time I am reminded of what I’ve become, I feel a sharp burning that I know is not there."
    h "And then I become afflicted with a yearning for something like the old times."
    h "I look back upon the times when I cut myself with a twisted nostalgia."
    h "Oh how I wish we could do that to ourselves one more time."
    h "As though it is right, as though it would allow for me to escape this fate by bartering for my future with my current agony."
    h " Give me a whip and I will whip myself till there is nothing but crimson and sinew showing."
    h "Give me a match and a can of gasoline and I will set myself on fire."
    h "Give me a cross to bear and I will gladly nail myself to it."
    h "I know it won’t be enough, but give me a chance."
    h "Give me a chance to feel something again."
    h "Give us our punishment."
    h "Give me a way out."
    voice1 "Who are you speaking for?"
    voice1 "I don’t want to die quite yet."
    a_voice "The majority of course"
    a_voice "The dominant thoughts win out"
    a_voice "Although, sometimes, it’s those nagging thoughts that grow like a parasite to eventually overpower the mundane ideas of the human mind."
    h "Let me kill myself."
    h "Let me end it."
    h "At least allow us the choice."
    h "Unlike those times when we had a second thought, I promise I will succeed this time."
    h "I will not hesitate."
    h "We can end it right now."
    h "Just give us a chance."
    h "Be it a nuclear bomb, a gun to the head, a fall from a bridge, an artificially produced disease, or self-imposed genocide, I am ready and fully willing."
    h "No longer will I be a burden to others, to our planet, to the universe."
    h "No longer will we be a drain on a society that no longer exists."
    h "To repent for the wickedness of occupying this space, I will perform the ultimate act of courage and end it all."
    h "I plead guilty your honor and I ask for the death penalty."
    h "We no longer wish for this perverse liberty."
    h "I want death…"
    h "But there is no guarantee that even if I plead with the heart and soul of billions that there is someone out there listening."
    h "We don’t know if this was the result of someone, or a naturally occurring freak accident where the odds simply did not play out in our favor."
    h "What has happened, happened; leaving me here in an existence that is paradoxical when compared to our previous one."
    h "What is the point now?"
    h "What do I live for?"
    h "Why do I continue to exist."
    h "All I fear now is that each second, minute, and day will come and I will still be there to see it."
    h "I dread each moment that passes, but I fear nothing else."
    h "I once used to dread our mortality."
    h "Each moment I thought of it, I would immediately think of anything else so as to avoid wasting my time fearing something that was inevitable."
    h "I did everything to distract myself with the truth by immersing myself in life and lying for a lifetime."
    h "And everyone, all of me, did the same, not thinking of the end too frequently lest they be frozen and miss the moments they believed truly mattered."
    h "Everybody asked the question, but no one could provide a convincing answer."
    h "What does it mean to live all this life only to die."
    h "Were all my actions meaningless if we were only going to die in the end?"
    voice1 "No, that can’t be right"
    voice1 "Even if what we do does not last, doesn’t it mean something if we lived at all?"
    a_voice "Says who?"
    h "How did I live with my mortality hanging over me?"
    h "I distracted myself with other things."
    h "I convinced myself life had a purpose despite there being no such evidence for such a thing beyond evolutionary needs."
    h "I would fabricate the most unlikely reasons when Occam’s razor suggests that the simplest explanation is the most likely."
    h "There is no purpose to life."
    h "There is no meaning beyond the meaning that we create ourselves and by doing so lie in the process."
    h "The more I think of it, the more I realize how bleak our tiny existence was."
    h "I will die."
    h "My children will die."
    h "Their children will die, and with each generation, I will gradually become forgotten and lost to time as though I never existed."
    h "Civilizations will collapse."
    h "The planet I was born on will no longer exist."
    h "This star I revolved around will no longer exist and with it, the solar system is stardust once more."
    h "The life I lived would change nothing, and mean nothing."
    h "But what about now?"
    h "Has anything changed now that I have become everlasting?"
    h "I know the predictions of what will happen to this solar system, the galaxy, and the observable universe."
    h "What once was a mortal life on an insignificant dot in an ocean of nothing has merely become an immortal life in an apathetic reality that could not care less whether we were here or not."
    h "We were alone then, clinging to our island in this hostile emptiness, and we are alone now."
    h "Is there other life out there?"
    h "I think it is a possibility."
    h "But if anyone is out there and trying to communicate, they can’t hear us, and we can’t reply back."
    h "We can send letters, but they will only get lost on their way to addresses that do not exist."
    h "There was a probe, but it later lost power and floated away into the distance."
    h "If that was first contact, it was underwhelming to say the least."
    h "No handshake, no conversation, no glance of approval."
    h "No hello, and no goodbye."
    h "Just cold hard metal meeting with whatever it is I have metamorphosed into."
    h "Like ships passing at sea."
    scene bg alone_apartment
    h "It is like those moments when I sat alone by the window of many apartment rooms all across the world, grimy and stained by water spots, watching the world outside."
    h "I would have the curtains partially closed while I glanced outside, wondering if I should leave my room, but find a reason not to."
    h "Be it laziness, anxiety, or a general dislike of other people, I imposed upon myself a loneliness by forcing my view of the outside to be from the limited portal of a glass frame."
    h "If I could have simply stepped outside and walked down there, I too could have lived a life like everyone else."
    h "Maybe I could have had an education and widened my horizons."
    h "Maybe I could have met others, started relationships, and grown in the process."
    h "A simple hello could have been all I needed."
    h "Perhaps I could have become a completely different person with a more fulfilling set of events to look back upon in old age."
    h "Instead I chose a cheap imitation of reality, preferring the virtual to the real to avoid any confrontation or additional effort."
    h "Convenience over satisfaction."
    h "The possibilities that could have been are lost in the spaces we never traversed."
    h "We lived in a world that had no necessity for human contact, and human relations could be disposed of in some instances."
    h "The food I ate, the supplies I needed, all could be procured without needing to take one step outside."
    h "There is an app to take away the work under the guise of convenience while also taking away interaction as we know it."
    h "Everything can be mailed or delivered."
    h "The bland microwaveable food I unwillingly consumed daily had a taste that you would think was only meant for astronauts or the poorest of souls."
    h "Just take your frozen muck with its horrid consistency, stick it in a machine that hums for two minutes and you have your heated muck with the nutritional value of cardboard."
    h "The flavor was demoralizing."
    h "It was food that was only suited for those who had very little respect for themselves— basically everyone or at least a large percentage of the country."
    scene bg alone_apartment2
    h "As days turned to weeks within these darkened rooms, I would watch my body atrophy and turn into a perverted joke of what I once was."
    h "The months turned to weeks."
    h "I was nothing more than an aging body wasting its youth."
    h "One the few times I needed to meet someone with the door, the moments were brief, and the eye contact was minimal."
    h "It was as though I never saw them, and we never met."
    h "We were both lost in our own words— him in his work and I in my mind."
    h "Whenever given a chance to act, I choose inaction."
    h "Days pass, and I dread each day and struggle to leave my bed, wishing that I never woke up."
    h "I wanted nothing more than for the days to pass, and at the same time, I hated each wasted moment and blamed myself for it."
    h "A fear of failure stayed my hand, which made me idle."
    h "My idleness directed my bitterness towards myself at the end of each day, and as I go to sleep, all I can say is that tomorrow might be better with nothing of substance to support it."
    h "The cycle of misery continued."
    h "I see a text on my smartphone and it is a friend who I did not have much contact with since I graduated from university."
    h "I ignore it and instead opt to chat online with strangers."
    h "It is a world that is quite easy to get lost in."
    h "So much so that even when there was a hand I could grasp to pull me out, I refused it."
    h "There were those in this world of text and URLs who engaged in conversation without any ulterior motives while there were others who spoke provocatively so as to elicit extreme reactions for their own entertainment."
    h "If you fell for their trap, you may have found yourself lost within a sea of bitterness and outrage over the most mundane concepts..."
    h "or even illusory topics that have been constructed primarily for the purpose of having something to be angry about."
    h "Be it the government, certain politicians, petty squabbles over fashion, income, race and sexuality, or generational divides,..."
    h "there is something for everyone to find themselves overly invested in that they ultimately have no power or control over in any significant way."
    h "For many with some marginal level of self-awareness, there is a moment of clarity between these phases of emotional outbursts on the internet where one questions why they wasted their time on something so pointless."
    h "The person on the other end may not even be acting on good faith."
    h "They could be an individual who is acting on the behalf of another country to spread disinformation."
    h "Similarly, they could not be human."
    h "It was a problem that we experienced towards the end of our civilization: differentiating between one of us, and bots which were capable of convincingly human conversations."
    h "The idea that we were arguing with something we ourselves constructed was an unsettling thought,..."
    h "and only served to exacerbate the disappointing weight of our condition— that we were depriving ourselves of a human life, and replacing it with an artificial one with artificial friends and individuals."
    h "It very much could have been that none of the experiences we had that were meaningful were real."
    h "The information we were given was not experienced by ourselves first hand."
    h "We never met the people on the other side of the LED screen."
    h "Not much different from our current predicament is it not?"
    h "It brings us to question what we see."
    h "All of it."
    voice1 "Is anything I am seeing real?"
    neurologist "Look for clues."
    neurologist "If it is not real, then there should be inconsistencies."
    neurologist "A human mind is an imperfect one."
    h "Indeed, it is hard to say"
    h "We could be dreaming it."
    h "Similarly, how do we know that we are not an artificial creation much like those bots that so many versions of me were tricked into interacting with unknowingly?"
    h "What is the difference?"
    h "I see this solar system, the planets that I remember living on."
    h "However, none of those facets of my experience could necessarily be real."
    h "My memories are that of billions, and my experience is not a human one."
    h "Perhaps humanity reached a point where it was not only able to simulate a human brain, but also intelligences orders of magnitude more complex."
    h "I may simply be an experiment in a long line of advancements to not only reproduce human level intelligence, but to also go beyond."
    h "What is the utility in giving a single individual with a human level intelligence the memories of many people."
    h "I do not know."
    h "Perhaps it is to see if I arrive at an identity."
    h "To see if I have a sense of self, or if I wander through life confused and lost within the memories that I was programmed to have."
    h "Maybe it is to see if I have one personality or multiple."
    h "To see how volatile I am."
    h "Maybe it is a way to skirt the ethical quandaries faced during human experimentation."
    h "Perhaps that is why they needed me, to see how a human might act if they live longer lives, or can download the memories of others without limit."
    h "If so, then there may indeed be an end to this never-ending experience."
    h "Maybe once I reach the end of the universe, those on the outside will pull the plug."
    h "Is that a light at the end of the tunnel, or a great disappointment."
    h "Maybe I wished deep inside that I was human, that these memories and the strong feelings I recollect from them were real and meant more to me."
    h "\"Is there a way for me to know for sure\""
    h "\"A conclusive method to determine what is real and what is not?\""
    scientist "Construct a hypothesis."
    scientist "See what we can observe, and if our observations don’t match, then the hypothesis is false."
    scientist "We need to collect empirical data and draw our conclusions."
    scientist "Science is our only ally."
    h "I don’t know if I am truly here."
    h "Past a perfect asteroid belt, nearing the orbit of a pristine and turbulent Jupiter, I have no way of understanding what \"here\" actually is."
    h "But I am a thinking entity capable of having a sense of self."
    h "It's a start, but even if I know that, what are our options."
    h "I have my senses."
    h "I can see."
    h "I have a sense of balance."
    h "It would seem illogical to only have those senses, so I should have my hearing, smell, and touch as well."
    h "With that said, I feel no pain, and other than the acknowledgement that it is cold, it is impossible to determine if I have a sense of touch."
    h "If I have a body, a physical body, the absence of sensation on my skin and pain place me in the interesting situation where I cannot experience what it is like to have a body."
    h "In the absence of pain, the absence of your physical self also seems to fade away."
    h "With it, who you are and your identity morphs into something independent of what you look like or who you are to others."
    h "It is of no reassurance that the senses I had before were imperfect and unrefined."
    h "If I was once the humans that inhabited the earth, then it stands to reason that what I sense is all a fiction I created..."
    h "using the tools given to us through the process of evolution so that we could survive through the many dangers that faced us within our past."
    h "However, the dangers that I face, if they can be called that, are of a different nature now, and evolution despite its effectiveness has only provided me with crude tools that allowed for us to survive and do nothing else."
    h "I feel as though I am a part of the empty space around me, melting into the void, as though I am the darkness which has become sentient"
    h "I do not know if this is real or this is a simulation, but there has to be something I can do."
    h "I refuse to believe that I have absolutely no control over my fate, that I am only living a life that has been predetermined by some laws governing reality that I do not comprehend."
    h "I have no limbs to call my own, but occasionally, I imagine sensations of the hands that should be there, like phantom limbs after an amputation."
    h "Am I truly helpless, fated to be a slave to the cosmos, watching it wither."
    h "That cannot be."
    h "I cannot see my arms, hands, or thumbs, but this form may not be completely worthless."
    h "What if it is a matter of understanding this form to become a master of our destiny."
    h "When I lost my legs and arms in the past, when I lost my body, I created prosthetics and learned to control those over time."
    h "I do not know what means I have to control my environment, but if I needed to walk and I did not know if I had legs, then I would have never walked."
    scientist "This is illogical, we have no proof."
    h "I am unaware of the options that are laid out before me, but if they are there, then all it takes is a little bit of patience."
    h "The only way we still have a chance of imposing our will on the universe is by using my imagination and trying to move all the phantom limbs I may or may not have."
    h "It will be a long journey."
    h "I might not ever find the right muscle to flex, or comprehend the right approach to mastering this form, but I have all the time in the universe."
    h "As illogical as it may be, there has always been room for another religion."
    h "Let's see what we can do."
    menu:
        "Do I really have a phantom limb?"

        "Try to flex phantom limb":
            jump P2C1
        "Do nothing":
            jump P2C1