# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

image bg first_steps = "P2C2/bg P2C2 A child taking its first steps.png"
image bg first_steps2 = "P2C2/bg P2C2 A painting of a child taking its first steps.png"
image bg blurry_childhood = "P2C2/bg P2C2 A painting of the blurry memories of childhood.png"
image bg blurry_childhood2 = "P2C2/bg P2C2 A painting of the blurry memories of childhood 2.png"
image bg blurry_childhood3 = "P2C2/bg P2C2 A painting of the blurry memories of childhood 3.png"
image bg blurry_childhood4 = "P2C2/bg P2C2 A painting of the blurry memories of childhood 4.png"
image bg blurry_family = "P2C2/bg P2C2 - Blurry memories of a family waiting for me at home.png"

label P2C2:
    scene bg first_steps
    show screen centeredbox("{size=+10}Chapter 8: The Miraculous Odyssey towards Adversity{/size}")
    pause
    hide screen centeredbox
    h "The memories of our early childhood are few and obscure."
    h "It is all a blur regardless of the life I lived, as though I've simply dreamed those moments."
    h "Things such as socio-economic conditions, the words spoken around me, where I've been, and where I planned to go were the first things I forgot."
    h "I was once a completely different person."
    h "However, who that person was is shrouded in the fog of time."
    h "What does stand out among the muddled past that is childhood are the senses and emotions— what I felt, when I felt them."
    h "The smell was also strangely vivid despite not knowing what it was."
    h "Was it plastic, or some kind of chemical in the common household like a fabric softener? Context is absent, and worries non-existent."
    h "I lived only in the present, unable to think back upon a past, and unwilling to ponder the future."
    h "Direction was a strange concept."
    h "I could move myself left, right, up, down, forward, and backwards, but not understand or comprehend a final destination in the initial stages."
    h "I thought not of where I should go, but simply what I wanted to do, and eventually I would arrive at my destination through a series..."
    h "of misguided actions where I crawled along to wherever I wanted to be without caring where I was, or what dangers were strewn along my path."
    h "It was instinct over wisdom."
    h "Feeling over experience."
    h "Present pain took any priority over future pain, and the absence of pain in the present meant the absence of pain in the future."
    h "There was only me, and what others could offer me."
    h "Cause and effect, action and consequence."
    h "None of this meant anything for me."
    h "I simply wanted."
    h "I simply did."
    scene bg first_steps2
    h "And in the process, I simply learned."
    h "Which brought me to the decision to take my first step."
    h "I am not sure what brought me up from the ground in all those lives."
    h "Was it madness, or a wish for greater freedom? Maybe it was the strings of fate lifting me up from the ground, pushing me in the direction of whatever I was meant to be."
    h "Maybe seeing those who cared for me walk unhampered made me realize my limitations."
    h "This clumsy body was clearly not enough for me despite it acting as a governor on my stupidity."
    h "I crawled along, sometimes on hard floor, sometimes on carpet, sometimes not even underneath a roof, but I crawled towards anything I could use to support myself."
    h "I would balance myself as I moved my body up the vertical support so that I could place my torso above my legs."
    h "This step alone was quite challenging, as I would often either slip and fall forward, or push myself up too hard, lose balance, and fall backwards."
    h "It was only through the process of repetition that I was able to place myself upright on two legs long enough that I had the leisure to look around at my accomplishments as though I were the ruler of a kingdom."
    h "Feeling ambitious, I might try to move onto the next step and put one foot forward only to fall flat on my face and then wail in response to this great injustice."
    h "Of course, this too would pass, and even the need for a vertical support would be unnecessary."
    h "Often, my efforts would be independent, but when they were noticed, I would receive help in some form or other."
    h "Those who cared for me would raise me up, catch me before I fall, and wait some distance away so as to encourage me towards a destination that was leagues away."
    h "I did not understand what they were saying, but what I could make out in the tone of speech, the facial expressions, and the body language, only convinced me that I was on the right track."
    h "I did not understand what a parent even was."
    h "I did not have a clear understanding on what our connection was, how we were related, or why I was being cared for despite expecting a certain level of care."
    h "In spite of this, I could feel something drawing us together."
    h "Perhaps to our parents, we were merely a burden."
    h "However, at the time, I felt a feeling of safety, of comfort."
    scene bg blurry_family
    h "I did not know or care to know of what I was being protected from, but I held the greatest confidence in the abilities of someone who I only knew for a short period of time."
    h "The moment I saw them, they had my trust even though I had no one else I could trust."
    h "There was a feeling of attachment I could not quite explain."
    h "If there was a place I could call home, it was because they were there, waiting for me."
    h "There was an emotional bond, built over a short period of time, a bond that had no backing."
    h "It was strong, and it was unconditional."
    h "Still, to this day, I do not know why I could foolishly conclude that those feelings of security, assurance, relief, and erratic joy which..."
    h "came and went were real, but my obstinate belief in my feelings rather than reality often led to those feelings becoming reality."
    h "That could be what it means to be family."
    h "While I did not realize it at the time, the impressive nature of what I did in those many instances does not escape me now."
    h "I used an undeveloped body with weak legs and stubby toes to walk."
    h "I know how difficult that is for animals, for robots, and even some people."
    h "Despite this, I succeeded billions of times while using tools that were only barely up to the task, like chopping wood with a dull ax, or starting a fire with merely twigs and rocks."
    h "It is possible, but it was laborious."
    h "Each day, with each time, I would add another step to my personal record."
    h "I would make it further and further, and my body would change and adapt to help me."
    h "Then, one day, I reached the end, and what was once one of the greatest challenges simply became a milestone on a series of landmarks along the way to old age and eventually death."
    scene bg blurry_childhood
    h "From that moment, my greatest concerns would continue to be forward looking, while occasionally being grateful for the past."
    h "I rarely considered the series of events that led up to this point, and took whatever occurred for granted irrespective of how improbable as though I deserved it and was entitled to it for simply being alive."
    h "Every time I looked back, all I thought was how quickly time passed as though everything was a whirl when in reality, the passage of time did not quicken nor slow."
    h "I did not worry about the probabilities involved in the formation of our star."
    h "I did not care about all that lived before us and the well tread path that was given to us."
    h "I did not consider the unlikeliness of my existence."
    h "To reach this point, an infinite series of events needed to occur."
    h "The universe needed to form, and our reality needed to have certain rules."
    h "Time needed to flow forward."
    h "Matter needed to exist."
    scene bg blurry_childhood2
    h "The Earth needed to be placed in the appropriate location within the solar system."
    h "It needed a moon and the gravitational force it exerted."
    h "It needed the right combination of elements and molecules and a certain amount of energy for the formation of the foundational building blocks of life."
    h "Life itself had certain requirements."
    h "It needed to be able to generate energy and grow over time, eventually reproducing."
    h "It needed a safe environment that did not change too often so that it was not wiped out completely."
    h "And that was the bare minimum before it could grow into more complex forms."
    h "The features of humans that were seen when I was still on Earth: multicellular structures, organs, vertebrae, limbs, sensory organs, a brain capable of.."
    h "complex behavior took billions of years and required many extinction events to allow for their development."
    h "We, the descendants of those who cowered before the apex predators of past eras only came into being because we had our chance to stand in the sun and grow unimpeded into the upright form associated with humans."
    h "It was luck, and little intention that brought us to this point."
    h "Evidently, the many factors that played a role were billions of years in the making and beyond our control."
    h "Even when considering events after the appearance of Homo Sapiens, there was no shortage of things that had to go right to bring us to this point."
    h "Ignoring all the inventions, the rise and fall of civilizations, when looking at what individuals themselves needed to accomplish, it is quite clear that all of the stars needed to align accordingly."
    h "Our ancestors needed to survive genocides, disasters, and outlive their competition long enough to form families and find offspring."
    scene bg blurry_childhood2
    h "What of my parents—these people who stood at the end of a room waiting for me to walk towards them with the utmost patience?"
    h "My parents needed to be born, and they needed to be born without severe defects or impairments."
    h "They needed to live long enough to reach the point where they could meet, know one another, and decide to stay together."
    h "They had to be in a position of relative stability, both in terms of maturity and finances to allow for the support of their future child."
    h "This typically meant being able to maintain a profession, having the educational credentials to gain that position, and the right type of upbringing needed to succeed within an imperfect educational system."
    h "Then, there is the task of conception, a stage where much could go wrong."
    h "The joining of gametes, a sperm and an egg cell, to fertilize into a zygote is one of a game of extreme probability and competition."
    h "Where one sperm cell ultimately fertilizes an egg, millions fail, and in the process the gender, and many of the genetic qualities of the offspring are decided."
    h "Two sets of twenty-three chromosomes join to become forty-six, forming a full genetic picture of who this child may become if all goes according to plan."
    h "What follows is the development of an embryo over the course of nine months as it divides and grows into a fetus."
    h "One often wonders when this collection of cells becomes a human, but what is quite clear is that there is a point where this alien soul turns from..."
    h "something subjectively perceived as merely a clump of flesh to something that might be more, something that is human."
    h "Where this point lies is unclear, and dependent on each person."
    scene bg blurry_childhood3
    h "To some, the child does not feel human even after birth, and it is only when it is able to express itself meaningfully that it is acknowledged as a human with intelligent thoughts and self-awareness."
    h "While for others, the human spark started well before its conception, as though the human was born billions of years before it even gained a physical form."
    h "There is no denying that the connection between the mother and the child leads to the question of whether these were two individuals prior to birth instead of just one."
    h "How connected are we, and are we more the same than we are different? We were all borne from the same processes, perhaps fated to exist from the moment the universe was incepted."
    h "Maybe we are simply many expressions of the same thing, and not truly all that different."
    h "Maybe we are not multiple individuals, but simply one being with multiple souls."
    h "Maybe the series of dominoes that led to this moment would always fall in the same way, leading to what I have become now."
    h "If we hate one another, then do I hate myself? When we were at odds with one another, was I simply thinking myself into a corner rather than working to solve the problems at hand?"
    h "Though I was given this chance, to exist despite all the challenges, maybe I squandered my chance, and continue to squander my chance simply due to my nature."
    h "The notion that I have nothing but squandered chances lying in store for me is a fear I have that dwarfs all other fears, and I am terrified that I can do nothing about it."
    h "Whenever I am reminded of this, all the joyful moments of the past morph into demons that torment me with prophecies of rapture and judgment in the future."
    h "To this day, I still do not know who I am, and what I want to be."
    scene bg blurry_childhood4
    h "I can barely remember the children I once were."
    h "In place of the childlike wonder I had and the liberty I felt despite being only a child, is a deafening cynicism that stands in stark contrast to what we once were."
    h "Whether this is cause to be afraid is something I have yet to know and yet I still dread whatever is to come next despite knowing nothing."
    h "The boundless nature of simply being is no longer."
    h "We have cherished it, and we have forgotten it."

    menu:
        "Try to flex phantom limb":
            jump P2C3
        "Do nothing":
            jump P2C3