# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

image bg zooming_through_universe = "P2C3/bg P2C3 A first person view of traveling through space at light speed in the style of Leonardo Da Vinci.png"
image bg traveling_for_centuries = "P2C3/bg P2C3 Traveling through the vastness of space for hundreds lightyears in the style of Henry Fuseli.png"
image bg galaxies_colliding = "P2C3/bg P2C3 Galaxies colliding in the style of Henry Fuesli.png"
image bg galaxies_colliding2 = "P2C3/bg P2C3 Galaxies colliding in the style of Henry Fuesli 2.png"
image bg galaxies_colliding3 = "P2C3/bg P2C3 Galaxies colliding in the style of Henry Fuesli 3.png"
image bg comets_bodies = "P2C3/bg P2C3 Comets and small bodies in interstellar space photorealistic.png"
image bg comets_bodies2 = "P2C3/bg P2C3 Comets and small bodies in interstellar space photorealistic 2.png"
image bg comets_bodies3 = "P2C3/bg P2C3 Comets and small bodies in interstellar space photorealistic 3.png"
image bg comets_bodies4 = "P2C3/bg P2C3 Comets and small bodies in interstellar space photorealistic 4.png"

label P2C3:
    scene bg zooming_through_universe
    show screen centeredbox("{size=+10}Chapter 9: Infinite Failure{/size}")
    pause
    hide screen centeredbox
    
    h "The sights I've seen have left an indelible impression on me that may last to the end of the universe."
    h "It is almost as though I could be misled into thinking the wait was worth it."
    h "We once believed that to see what, in the past, could only be viewed from far away with a telescope up close would be an impossibility that I would never experience within my lifetime."
    h "However, I have been given the privilege of exactly that, and for that I am grateful."
    h "In exchange, we were required to temper our patience to a level we have not reached before."
    h "A level that is orders of magnitude beyond any meditation, any prison sentence, and any ordeal."
    h "The human mind was not designed for such a thing, and yet here we are."
    h "It is a mental marathon of unprecedented proportions."
    scene bg traveling_for_centuries
    h "It seems that our plight was predetermined and any struggles were ultimately futile."
    h "In such a situation, patience and resilience were the closest thing to stopgaps which could save us from the periodic episodes of plunging into mental abysses from which we escaped only by clawing our way out."
    h "It was a meager existence of falling in and climbing desperately out over and over again with no end in sight."
    h "To expect anything was a worthless enterprise."
    h "Initially, there was hope, or at least more of it than there is now."
    h "Jupiter, the ruler of this outer realm, shined with a brilliant light and is adorned with spots that glow like embers in the night sky."
    h "Its gaseous exterior, a tapestry of golds, oranges and reds, created a visage of grandeur and splendor that acted as a lantern in our lonely travels."
    h "Past the orbit of Jupiter, we watched ourselves fly off into space, with increasing speeds over the centuries and millennia."
    h "Time was something we had no shortage of, but the smallest of pains and most miniscule of ordeals could lengthen time like a black hole tearing apart matter and stretching it into unimaginably long segments."
    h "The time I spent to reach where I am now has been long, but it felt longer, and eventually, it lost the meaning that it once held to a being with a mortal's perspective."
    h "In a life with seemingly infinite time, there is no such thing as incorrect actions, imperfections or failures."
    h "Anything that is wrong can be corrected."
    h "With that said, when you are incapable of doing anything, you cannot make a mistake even if you tried."
    h "Similarly, if you did something wrong, you are unable to correct it."
    h "In the place of action is an emptiness that emanates from this existence to watch time flow as you are unable to do act."
    h "Free will as I knew it was a thing of the past."
    h "I could not impose my will upon the universe or reality."
    h "Almost everything was as though it is set in stone."
    h "Everything, but the universe around me."
    h "It still endured."
    scene bg comets_bodies
    h "The universe I saw was beautiful."
    h "That much was undeniable."
    h "However, it was unbearably cold and unfeeling."
    h "When you look into the lights off in the distance, you can use your imagination, but it is anyone's guess as to whether someone is looking back."
    h "As I accelerated and left the domain of planets and entered the realm of comets and interstellar space,"
    h "I found myself missing the large companions that were among the closest things I could call friends in this island of matter floating in an ocean of empty space."
    h "It is undeniable that the more mass there is accumulated, the more chances there are for something interesting to happen."
    h "It is hard to create storms on an asteroid, or life on a small rock."
    h "You need size for that, and a lot of it."
    h "The smaller bodies have no moons, no core, no magnetic fields, and are basically fodder for the larger planets, or orphaned in space where nothing can touch it."
    h "Out there, in the space between systems, the pull of gravity is weak, and if you were stranded out there with no fuel, all you can do is simply wait and hope that you can be saved as your..."
    h "distance from any nearby stars implies that you won't be lucky enough to be within the gravitational pull of any system."
    h "I, however, am no astronaut, cosmonaut, or taikonaut in need of life support."
    h "There is no one here to save me."
    scene bg comets_bodies2
    h "The empty region between these systems is where I spent billions of years, waiting for whatever it was that propelled me to send me along my way to a place that was not simply black."
    h "It was once I reached Proxima Centauri that I realized how quickly I was traveling."
    h "Although it was not even remotely close to the speeds reached by the Voyager probes, it was fast enough to ensure I did not overstay my welcome."
    h "I was only within the system for hundreds of millions of years."
    h "I understood then that my destiny was one of multiple systems, and of many sights."
    h "While reassuring, this fact led to poisonous anticipation."
    h "I zipped past the planets of Proxima Centauri, appreciating its similarities to and its differences from our own sun."
    h "Proxima Centauri, unlike our own sun, was significantly smaller as it was a red dwarf."
    h "In our time, it was a faint star that was dismissed as being capable of holding life."
    h "Whether that dismissal was fair or not is questionable, but it is true that even the faintest of stars can be incredibly luminous up close."
    h "A large ball of fire is still a large ball of fire and its intensity was befitting of its pedigree."
    h "A star is still a star no matter how small."
    h "It was here that I noticed that I had a follower."
    h "The descendants of whomever sent the first probe had sent another one which matched pace with my predetermined path."
    h "Its droplet-like form glistened when it caught the light at the right angle and made for a welcome presence in an otherwise desolate scene."
    h "I wondered then whether the makers of this machine lived nearby— perhaps in one of the planets I had passed."
    h "What about the planets orbiting my sun? Now that I am gone, who is it that calls it home?"
    h "Perhaps someone more responsible is in charge now."
    h "Maybe my follower occupied the planet and terraformed it for their needs."
    h "Conversely, one of the other residents of Earth may be filling our shoes."
    h "I wonder which species it might be."
    h "The dolphins were limited to the oceans."
    h "The elephants are quite intelligent, but would they be able to match what we did in our prime? The chimpanzees and bonobos have a chance."
    h "When we still had hands, we could communicate using sign language and pass on knowledge in a somewhat limited capacity."
    h "Oh how I wish we could see what happened, what unique forms of life could flower in our absence."
    h "I could only grab a glimpse of this probe when it was in front of me, and when I did, I was unable to understand its form."
    h "How was it manufactured? What is it made of? How is it traveling? I was so curious."
    h "Here, in front of me was a probe far more advanced than anything humanity had ever built."
    h "It was smooth, beautiful, and unmarred as though it was more a striking work of art instead of a spacefaring vessel."
    h "The materials and the methods by which it moved were beyond our intellect."
    h "It was proof of a civilization that managed to live long enough to avoid the mistakes we made."
    h "What did the people who made this look like?"
    h "Were they like us with symmetry, with a vertebrae, two legs, and hands with opposable thumbs?"
    h "Or were they completely alien, taking on a form that we could not even imagine?"
    h "Perhaps they were not even carbon based or used DNA as a form of genetic storage."
    h "Maybe they were no longer biological."
    h "I hoped we have similar values, and a similar sense of wonder towards everything."
    h "I hoped that if we could communicate that we would be able to find common ground and understand one another."
    h "If intelligence is accompanied by curiosity and a balancing of exploration and exploitation of the environment, then maybe we are more similar than we think."
    h "Indeed, the cosmos is too barren for what little life that sprouts to regard everything with suspicion all the time."
    scene bg comets_bodies3
    h "These past musings only served to keep me entertained, but I was ultimately unable to answer a single question."
    h "Once I passed Proxima Centauri, my path approached several systems, but ultimately never entered their orbit, and I could only watch as these systems swung by on my flight towards a nebula."
    h "The swirling clouds of gas and dust that made up these nebulae, danced and played in a cosmic ballet, creating patterns and shapes that seemed to defy imagination."
    h "Their vibrant hues, ranging from deep blues and purples to fiery oranges and reds, painted a canvas of color that was both mesmerizing and awe-inspiring."
    h "From a distance, this bright cloud of gas and particulate matter was an imposing structure which colored the tapestry of the galaxy felt as though..."
    h "it was a solid body that held as much activity as an asteroid field, but upon my entering this cloud, I could clearly understand that it was more impressive from afar than it was within."
    scene bg comets_bodies4
    h "The gas and matter that colored the nebula was extremely diffuse which meant that like all things in the universe, the majority of it was composed of empty space."
    h "There is so much all around us, but when viewed in close proximity, it just looks like empty black."
    h "It was when I reached budding stars and planets which grew from the dust that I could truly savor and appreciate the existence of these clouds of matter."
    h "It was here that I could see the formation of solar systems much like my own right before me."
    h "These balls of dust could one day be home to life of its own which grows to reach for the stars much like my companion has and I did in the far past."
    h "As I passed through the clouds and continued on my way, I watched on, hopeful and almost envious of the opportunity that lay ahead for the life that would inhabit these systems."
    h "By this point, my speed was an order of magnitude higher, and my visits to systems increased tenfold, granting me the opportunity to see many more unique sights at higher frequency."
    h "All while gaining more followers."
    h "I ran the gamut of the cycle of life for stars."
    h "There were stars of differing colors from those which matched the white of our sun to others which were older and grew to red giants, swallowing its closest planet."
    h "I was in the center of a dead system when a white dwarf rained fire across space in the form of a supernova."
    h "Finally, I had the chance to see my first black hole."
    h "Rather, I did not necessarily see it, but I saw its effects."
    h "I observed how it used its gravitational heft to swallow all matter that unwittingly entered its pull."
    h "I saw how it bent and warped light to show us hints of what lay on its periphery."
    h "It made no sound, but I imagine if it could, it would have had a deafening roar that tore across the galaxy unheard by none."
    h "As I passed through the gravitational pull of the black hole unimpeded, my follower needed to take the long way around to meet me on the other side."
    h "The sight of light warping into strange geometries as I approached the center was bizarre, and it led me to question all the theories that were formulated in the past."
    h "While I could simply pass through, my followers had to utilize the black hole to slingshot themselves in my general direction..."
    h "so that it was able to keep up, and in the process, most likely experienced untold amounts of time dilation."
    h "I do not know what the lifespan of the creatures that built these spacefaring objects are, but what is clear is that they have either exceeded and surpassed biological limits, or that such limits no longer apply."
    h "If they could keep pace with me for millions and billions of years, then it stands to reason that the probes were not carrying biological life."
    h "If so, what does that imply for the civilizations that built them?"
    h "Were these machines simply carrying out instructions given to them without end while their masters crumbled away into dust due to the passage of time?"
    h "Or have the makers of these machines transcended life and death? I hope that the friends I have yet to meet are not already gone."
    h "In the end, I inwardly decided to move on, and these questions faded away as I continued to accelerate."
    h "I was hoping I could catch my former solar system if it had not turned into a shell of its former self through some disaster or as the result of simple aging."
    h "This was not to be, however."
    h "Reality was unfortunately not merciful, and we missed it by tens of thousands of light years."
    h "Our last chance of seeing our former home was ripped away by the cruel touch of reality which decided that the path we must take was in a different direction."
    h "Instead, we continued our tour of the galaxy, passing much of what it had to offer to arrive at a ternary collection..."
    h "of black holes slowly revolving around one another in a ballet of destruction, turning all within its surroundings into emaciated ghosts."
    h "Light played in this configuration like a demented prism, not simply being warped, but also mirrored in some cases."
    h "In a moment of what I believe to be the benevolence of fate, I was in the right position at the right time as a star passed by my position, lighting my body in visible light, and granting me a muddied look at what I had become."
    h "Off in the distance, as though there was a copy of me out there, I could see an image of myself and my followers contorted by the effects of gravity."
    h "A large mass, uneven and bizarre floated across the sky with shining metal behind it like a piper leading mice."
    h "It held the consistency of discolored meat, with uneven growths all across it."
    h "Like something mutated by radiation, it was inconsistent, and yet it had a familiar geometry like a polyhedron formed of multiple spheres."
    h "I could not place where I last saw a similar thing."
    h "Was it fungus? Perhaps a plant of some kind."
    h "Regardless, it felt alive, and that was what was most terrifying."
    h "That something so large could have a mind of its own and intrude upon any corner of the universe unimpeded."
    h "It moved consistently— more like a robot with a set of preprogrammed actions than a creature with a set of emotions and motivations."
    h "There was no sense of exploration, curiosity, or discovery in its movements."
    h "It was simply a large mass of flesh following a path as though wherever it needed to go, it needed to reach it quickly and efficiently."
    h "This scene was the first and last moment I would see of myself."
    h "Any changes and developments, good and horrifying, would go on to be unobserved by us in our future wanderings towards the end of time."
    h "That was when I began to lose track of time."
    h "I would count inside my head, keeping track of the seconds, or at least trying to achieve a close estimate."
    h "At some point, I simply gave up, and the increasing speed was of no help either."
    h "Although my perception of time may explain how much time passed for me, it does not tell us how much time has passed in the greater universe."
    h "I left the Milky Way galaxy with my companions in tow and left for the realm of nomads, strangers, and orphans, where everything was an endangered species."
    h "Here, there was even less than there was in the emptiness of the galaxy."
    scene bg galaxies_colliding
    h "The spaces grew wider, and I began to approach speeds that resulted in time dilation."
    h "I felt as though I was chasing after cars and watching them fly away."
    h "Whatever light there was formed streaks in my vision, blurring my periphery while the galaxies off in the distance shone brightly in a seductive manner."
    h "They were beckoning to me to visit."
    h "I realized, however, that the chances of sojourning to such large places were slim."
    scene bg galaxies_colliding2
    h "As far away as planets and stars were from one another, that did not even remotely compare with that of galaxies."
    h "Even the Andromeda galaxy, which was our closest neighbor, was millions of light years away, and at this point, I understood that the world of matter and light was.."
    h "in the minority, and nothingness was to be my reality for the foreseeable future."
    h "Even with the dilation of time, it is still a long period of time to witness the dying of creation."
    scene bg galaxies_colliding3
    h "It was just like that stage in life where I was behind bars in a cell."
    h "Time passed, but I could no longer tell."
    h "The outside world to me was just bland concrete and unchanging routine forced onto all of us at the prison."
    h "The meals were the same, the smell was the same, and nothing changed."
    h "But I knew and everyone else knew that the world was changing."
    h "It was changing without us, running on its own schedule, moving on without us."
    h "We were no longer needed."
    h "We no longer mattered."
    h "The tick tock of the world would not stop just because I was not there to witness it myself."
    h "My family moved on."
    h "They had no choice but to move on, and I needed to resign myself to this fact."
    h "My needs were nothing, and it was only selfish for my situation to hold back the lives of those I loved."
    h "It must have been the same for everyone else."
    h "I know it was the same for so many of my lives that spent significant portions of their time incarcerated."
    h "God has left the building, and did not take me upon his exit."
    h "The unreasonable nature of the situation did not matter."
    h "Whether I spent my time inside an empty apartment, a jail cell, or strapped to a hospital bed, no one cared who I was."
    h "No one cared if I lived or died."
    h "I was just one in billions, a drop in a sea of people."
    h "It does not matter what I think, the rest of reality moves on."
    h "It did not revolve around us back then, and it did not do so now."
    h "The center of the universe is elsewhere."
    h "It is anywhere except where I am."
    h "Here in this cell, there is only me."
    h "There is not much space to move, but there is much time to think as I stretch my limbs every time they start to cramp."
    h "Regardless of where I was, where I am, when I lived, and who I am, the only thing I was entitled to were my own thoughts, and now, those were the most valuable possessions I had."
    h "The universe may forget us, but we refuse to forget ourselves and lose ourselves within the void."

    menu:
        "Try to flex phantom limb":
            jump P2C4
        "Do nothing":
            jump P2C4

