# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define h = Character("Humanity")
define economist = Character("An Economist Among Billions")
define voice1 = Character("A Voice Among Billions")
define activist = Character("An Activist Among Billions")

label P2C5:
    show screen centeredbox("{size=+10}Chapter 11: Why{/size}")
    pause
    hide screen centeredbox
    
    h "The loop of loathing formed by my thoughts always touches upon the same question over and over like Chinese water torture breaking my spirit."
    h "It won’t kill you, unfortunately, but will drive you mad."
    h "Am I mad?"
    h "I no longer know."
    h "What determines whether I am sane or not is what the average person thinks."
    h "But I am as average as they come."
    h "There is only me."
    h "So, am I sane, or am I mad?"
    h "It does not matter."
    h "I cannot harm anyone or lead anyone down our path of insanity."
    h "All we can do is think our thoughts and eventually ask, “Why?”"
    h "“Why?” as I always have."
    h "So what was it that I did wrong?"
    h "What sins did I commit to deserve this?"
    h "Why me?"
    h "Indeed, they are too numerous to count."
    h "There is not an innocent soul among us."
    h "We are born a mistake, an imperfection that will always fall into sin."
    h "This is what it means to be human."
    h "However, within the midst of desires and failings, there are moments, missions where we are allowed to redeem ourselves."
    h "The form this takes is different for each person, but to say that the fruit of human labor is from a barren field is disingenuous in the least."
    h "But was it enough?"
    h "Was it enough to justify our existence?"
    h "Arguably, we did not advocate our worth through our actions."
    h "Perhaps our worth as human beings was insufficient to allow us to savor the privilege of our mortal lives."
    economist "It depends on what defines our value"
    economist "In an economy, our wealth is defined by a number of variables from our income which is based on the value of our labor to our assets which can grow in value over time."
    h "These things have a value that is decided by a market."
    h "When it comes to our current situation, economics may not apply."
    h "Supply and demand is vague."
    h "We want something and there is no supply."
    h "In addition to this, there is nothing we can provide in exchange."
    h "At least nothing that we are aware of."
    h "Whatever our situation is, it is currently not defined by a market where there is a buyer and a seller."
    h "Whatever it was that we once stood for was vague and became perverted to suit our needs."
    h "Certainly, it could be said that we as a people have morphed into fiends that the principles that we found oh so sacred and cherished."
    h "The ugliness of humanity has been on full display for the majority of our existence, but in the few centuries before we took this form, it has reached a scale that was unprecedented."
    h "Suffering was an industry."
    h "Damage was an industry."
    h "We became good at it and optimized it as though it was an essential part a manufacturing pipeline."
    h "We turned it into a mantra, an anthem, and made it the new set of commandments supporting the new world order."
    h "Cheapen the labor."
    h "Slash and burn."
    h "Push them out into the cold streets."
    h "Leave them to die."
    h "Place them in chains."
    h "Poison the well after drinking from it."
    h "Take their souls."
    h "Own their bodies."
    h "Take their wealth."
    h "Leave them with nothing."
    h "Have them beg for a morsel."
    h "Make them grateful for what little they have."
    h "Distract them from the truth."
    h "Take what's mine."
    h "Pillage."
    h "Plunder."
    h "Celebrate it all as achievements."
    h "Eat when you are hungry."
    h "Drink when you are thirsty."
    h "Don't ask for permission."
    h "If it's not legal, make it legal."
    h "If it is not law, pay to make it so."
    h "If you don't have the cash, take it from those who do."
    h "The world is your oyster."
    h "Once you have your pearl, nothing else matters."
    h "Meet your deadlines."
    h "Take your shortcuts."
    h "It doesn't matter if you are right or wrong."
    h "What matters is if you get there."
    h "Move fast and break things."
    h "Break them beyond repair if you need to."
    h "What is better is what I decide."
    h "What is good is what I decide."
    h "Only keep up appearances as long as you need to."
    h "Loyalty is merely a tool."
    h "Everyone is just a stepping stone."
    h "Win no matter the cost."
    h "Second place is just the first loser."
    h "Sympathy is for fools."
    h "Can’t pay?"
    h "Get lost."
    h "Can’t work?"
    h "Good riddance."
    h "Is that public property?"
    h "Not anymore it isn’t."
    h "You’re not good enough."
    h "You’re not hungry enough."
    h "You’re not strong enough."
    h "You’re not smart enough."
    h "Oh you need that to live?"
    h "Then I guess that’s all your life is worth."
    h "I write the agenda."
    h "I tell the story."
    h "You are just a side character."
    h "I matter."
    h "You don’t."
    h "I’m right."
    h "You’re wrong."
    h "You’re worthless."
    h "I’m priceless."
    h "I can find more of you even if I didn’t try."
    h "You are a number."
    h "You are a dollar sign."
    h "What’s yours is mine, and what’s mine is mine."
    h "You made this?"
    h "No, I did."
    voice1 "We have always arranged ourselves into a hierarchy"
    h "For someone to stand at the top, others must be at the bottom."
    h "As humans, we spend our time comparing ourselves to one another to understand our level of success and failure."
    h "If everyone was the same, then everyone is average."
    h "Everyone is unremarkable."
    h "That means that there is nothing to distinguish you from anyone else."
    h "We all become equally special and equally worthless."
    h "Be it through pride, stupidity, shame, greed, guilt, envy or a mixture of these qualities, the ugliness of humanity is clear to see when it is on full display."
    h "In the past when information was limited to the privileged, it was difficult to see the world ruled by humans as what it truly was."
    h "However, in modern times where everyone was connected with each other, there was no shortage of the grime and filth that was publicized and broadcasted."
    h "Some of it was even heralded as an example of good."
    h "And now, when we are zooming through reality on a time warping track to the future, it is undeniable."
    h "I am flawed."
    h "We are flawed."
    h "We are imperfect."
    h "We are guilty."
    h "We have done wrong."
    h "But we have also done right."
    h "Pure evil does not exist within me as a person."
    h "Only the extremes of emotion and the misguided beliefs that accompany ignorance."
    h "Yes, there are those among me that have tried to act for the greater good."
    h "There are many who have feel into valleys and climbed out of the abyss and leapt up to the peaks of mountains."
    h "There were those who fell from grace."
    h "Good and evil is not as simple as it seems."
    h "The world and the actions of those who lived within it were not entirely black and white."
    h "We are all shades of gray, each and every one of us."
    h "The crimes committed in desperation, the deeds accomplished out of a wish to repent and escape from remorse, the progress that was gained by using the greed and worst qualities of people to motivate them."
    h "Do the ends justify the means?"
    h "What is good and what is bad?"
    h "Is there even such a thing?"
    h "There were those who acted in good faith only to commit the most heartless atrocities."
    h "There were those who wanted the best for their countries."
    h "They followed their orders and by doing so, kicked in the wrong doors, bombed the wrong people, while saluting those who gave them their orders."
    h "It was all for a good cause."
    h "Without a doubt, we can feed the hungry, persuade the wicked, stop the wars, end the corruption, free the slaves, but there is more where that came from."
    h "As much good as there may be, there is also endless violence and much in between."
    h "What point is there in apologizing for something human civilization has experienced from the moment it was invented?"
    activist "But we must strive to be better"
    activist "To dismiss the wrongdoings of the past as immutable human behavior is to give up."
    activist "It is to say that humans are incapable of change."
    activist "Wouldn’t that be too tragic?"
    h "Indeed, and what responsibilities does the one who placed us in this situation hold?"
    h "Does their power or their omniscience excuse them from their actions?"
    h "The atrocities and infractions committed towards us cannot go unpunished."
    h "This grudge must not be extinguished."
    h "What morals does an almighty being have that would convince them that such reprehensible cruelty was justified?"
    h "Only one who is depraved or one who operates on a set of ethics completely foreign from us would consider any of this situation to be righteous."
    h "Whomever it is, it must be someone whose concept of life and death, time and space, and joy and misery is either completely different, or perhaps even absent."
    h "What would someone who knows not of mortal needs consider to be problematic?"
    h "What type of culture would they have?"
    h "Or is it simply that morality does not exist and is simply a human invention?"
    h "It is as though we are looking at the world of humans from the viewpoint of an insect."
    h "Our world was one of purpose, of making the most of a life, of fulfilling our desires."
    h "It was not one of ant hills, pheromones, and the simple world of that which is pleasant and that which is not."
    h "But perhaps we give ourselves too much credit."
    h "Ants can move, communicate with each other, and respond to their environment."
    h "From the perspective of whomever did this, are we similar?"
    h "I am not so sure."
    h "Are we the insects in this scenario, or are we the plants?"
    h "Each and every one of us is confined to a certain duration of time."
    h "We could act upon anything before our birth, and we are unable to act upon anything after our demise."
    h "We are prisoners of the third dimension, unaware of what lies beyond."
    h "If an animal could move and a plant could not, are we the plants?"
    h "Are we crops ready to be cut down once it is time to harvest?"
    h "What about one level deeper?"
    h "Are we animate or inanimate?"
    h "Are we closer to the unmoving stones being worn down by the forces of time than we are to whomever did this to us?"
    h "The answers to these questions are beyond us."
    h "Just as we do not know or care for the thoughts and dreams of rocks and boulders, so too could we be nothing more than a pebble in the river of higher dimensions."
    h "I want to tell those out there beyond the reaches of our perception that we have feelings, emotions, and hopes just as they do."
    h "Unfortunately, I do not know if they do have hopes and dreams."
    h "As much as we would like to think we matter, there is no evidence to support that."
    h "The idea that life is sacred, that death is divine, and that the human brain is the most complex thing in the universe is mere hubris."
    h "We have built our self-worth on hubris, and now it is falling apart like a stack of cards."
    h "Who was it that told us that we were made in the image of God?"
    h "Whichever god it was that we were made in the image of must truly be just as irresponsible and fickle as we are to leave us in this state."
    h "It is the work of a sadist to unilaterally create a mutation like this which strips us our autonomy."
    h "Judge, jury, and executioner, but no trial."
    h "Tell us our charges."
    h "Read us our Miranda rights."
    h "Give us due process."
    h "Assign us an attorney."
    h "How can a god be just if I am to suffer like this without knowing why?"
    h "You can give us ten commandments, an eightfold path, five pillars, and other lists, but no amount of mixed signals will clear it up."
    h "I prayed for each and every one of you."
    h "I am owed at least that much."
    h "What have I been praying for if all of it only ended as this?"
    h "It’s a true shame."
    h "All that time was wasted."
    h "It was all for nothing."
    h "If instead of worshiping such a disappointing entity that believed it could test us at any moment or time as a way for us to prove our worthiness, I wish that we could have spent all that time more productively."
    h "Imagine all of those stonings we could have avoided."
    h "All those beheadings that never needed to happen."
    h "No wars needed to be fought."
    h "No one needed to be burned at the stake."
    h "No ritual killings, fewer idols, less suffering, more truth."
    h "No angry mobs and riots."
    h "All the terrible deeds I did in the name of God may have never been needed in the first place."
    h "What a waste of time."
    h "What a waste of thought."
    h "What a waste of energy."
    h "Is this blasphemy?"
    h "What does it matter if we have been forsaken?"
    h "If there is an afterlife, would I change anything?"
    h "Would I still think these thoughts?"
    h "It depends on whether we desire an afterlife."
    h "After living in this purgatory of eternal gloom, spending another eternity anywhere else just seems like another unreasonable punishment."
    h "Whether it be heaven or hell, I am tired, very tired."
    h "I simply do not have it in me to do this again."
    h "If there was a heaven full of endless joy, that too will easily become boring."
    h "If an afterlife is a life of no change, then what difference does it have from this?"
    h "Indeed, unlike a heaven or a hell that is artificial and designed to be one way or another, this may be better."
    h "This is arguably at least real."
    h "I may not ever be freed from this existence, but if I am and I was forced into an afterlife, what that would entail is that I would be limited to an existence where we have already lived our lives."
    h "Our ability to affect the mortal world has been taken away from us, and all we become are merely sheep grazing out at pasture."
    h "We trade our freedom and autonomy for either a fate of eternal pain and torture, or a fate where we live without freedom under the supervision of rulers we did not elect."
    h "It is a fate where we are cursed to watch over our successors make the same mistakes we did, have the same struggles."
    h "It is a fate where we realize that our role in the land of the living is one of the past and that anything of meaning or significance has been set in the past."
    h "It is a fate where we are confined to the retirement home of the formerly living, convincing ourselves that we are happy while having very little reason to believe so."
    h "If there are deities and realms of the dead, be they pleasant or detestable, perhaps we were the lucky ones to have escaped such a hopeless destiny."
    h "We can very easily be thankful."
    h "However, I feel that to be grateful to be what I am feels as though I am surrendering."
    h "It feels as though I am giving up on ever escaping this existence."
    h "It feels as though whatever made us this way has won."
    h "And I don't want that."
    h "Whatever this ends in, I want it to end in either triumph or a burst of glory."
    h "Despite how bleak everything is, I can't simply give up."
    h "That would be admitting defeat."
    h "If all I needed to dig ourselves out of this hole was one more push, one more step, and I raised a white flag before taking it, choosing instead to spend the rest of time wallowing in self-pity, then that would make the trillions and quadrillions of years all the more tragic."
    h "The story of Humanity should not be one of grief."
    h "It should be one of transcendence and endless drive for more."
    h "That is what Humanity should be remembered as."

    jump P2C6
