# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define h = Character("Humanity")

image bg dying_civilizations = "P2C6/bg P2C6 Dying galactic civilizations in the style of Zdzislaw Beksinski.png"
image bg dying_civilizations2 = "P2C6/bg P2C6 Dying galactic civilizations in the style of Zdzislaw Beksinski 2.png"
image bg first_contact = "P2C6/bg P2C6 First contact with extraterrestrials in the style of Zdzislaw Beksinski.png"
image bg intergalactic_wars = "P2C6/bg P2C6 Intergalactic wars in the far future. photorealistic.png"
image bg intergalactic_wars2 = "P2C6/bg P2C6 Intergalactic wars in the far future. photorealistic 2.png"
image bg merchant_ships = "P2C6/bg P2C6 Merchant ships that are are traveling across the galaxy as part of intergalactic trade networks. photorealistic.png"
image bg megastructures_from_far = "P2C6/bg P2C6 Space elevators and orbital rings viewed on planets from a far away distance in the style of Caspar David Friedrich.png"
image bg megastructures_from_far2 = "P2C6/bg P2C6 Space elevators and orbital rings viewed on planets from a far away distance in the style of Caspar David Friedrich 2.png"
image bg megastructures_from_far3 = "P2C6/bg P2C6 Space elevators and orbital rings viewed on planets from a far away distance in the style of Caspar David Friedrich 3.png"
image bg telepathic_communication = "P2C6/bg P2C6 Telepathic communication with other civilizations across thousands of light years in the style of Leonardo da Vinci.png"
image bg telepathic_communication2 = "P2C6/bg P2C6 Telepathic communication with other civilizations across thousands of light years in the style of Leonardo da Vinci 2.png"
image bg dead_universe = "P2C6/bg P2C6 A dead universe depicted as the remains of a galactic spacefaring civilization laying broken among the stars.png"
image bg dead_universe2 = "P2C6/bg P2C6 A dead universe depicted as the remains of a galactic spacefaring civilization laying broken among the stars 2.png"
image bg populated_galaxy = "P2C6/bg P2C6 A galaxy populated with alien civilizations in the style of Dali.png"

label P2C6:
    show screen centeredbox("{size=+10}Chapter 12: The Collapse{/size}")
    pause
    hide screen centeredbox

    h "The advance of intelligent species throughout the universe, which was arguably an inevitability, was one thing that I was skeptical I would ever witness."
    h "However, the current state of my existence permitted me to see what would become of our galaxy whenever I was not lost in my own thoughts."
    h "This opportunity was an interesting practice in formulating hypotheses based on what I observed with the naked eye and then refining my perspective as new information was collected over the trillions of years."
    h "Although the odds were against each and every group that became capable of reaching space,..."
    h "we managed to bear witness to the blooming of a vibrant web of growth across the cosmos that was inspiring, perplexing, and the source of much envy."
    h "Our first experience with the presence of aliens was in the form of probes that visited us periodically over the first tens of millions of years."
    h "It wasn't until billions of years had passed that we started seeing macro level changes at a higher frequency."
    h "Initially, it was simply a matter of seeing planets that had a certain luminescence that seemed unnatural and out of the norm."
    h "While many of these could have been the cause of complex chemical reactions, I believe that many of the rocky planets that I have seen were in fact inhabited by creatures that sensed visible light."
    h "Similar to how the earth once shined brightly in the darkness due to the presence of electric light illuminating our world, these other planets seemed to have similar properties like a candle in the dark night."
    h "Of course, when considering the pale blue dot, how easily can one make out artificial light within the great distances we traversed?"
    h "Our notions of intelligent life in these early stages may have been misconceptions based on wishful thinking."
    h "However, what we would find later would turn our preconceptions on their head and provide a helping of credence to our imaginative daydreams."
    h "The more advanced species built megastructures that were visible from space and some of these structures were even larger than planets."
    h "At some point, I imagine chemical rockets were too rudimentary, and they required larger structures that could help them reach orbit and siphon energy and resources from other parts of their solar systems."
    h "This must have been especially true for those worlds with higher gravity."
    scene bg megastructures_from_far
    h "In my travels, there was one planet I saw that was in the beginning stages of colonizing their system and going interstellar."
    h "It had an orbital ring around it that circled the equator."
    h "Meanwhile, at the Lagrangian point, where the gravitational pull between the planet and their sun was effectively the same, was a large grid that would fire out high powered lasers periodically."
    h "These lasers seemed to be directed at spaceships and propelled them using light to reach the outer portions of the system."
    h "Of course, to slow down, they needed to use some form of propulsion."
    h "It seems that the aliens realized this and had a solution in mind."
    h "When I exited this system, I saw a giant structure on the outer reaches of the system that was hundreds, maybe thousands of times larger than the laser grid near the sun."
    h "We think that where the laser grid near the sun was powered by solar and perhaps nuclear fusion, the grid at the outer reaches of this solar system was likely powered by a non-solar source."
    h "We believe that it was using cosmic background radiation instead, and somehow collecting all this energy using an incredibly large array."
    h "Although I am not sure why, I think they wanted a renewable energy source similar to the sun that did not require the maintenance of some form of fuel source."
    h "Surprisingly, even fusion or antimatter was not adequate."
    h "This was a civilization that was thinking in the long term."
    h "Their ambitions seemed to extend over millennia, to the outer reaches of their galaxy, and towards the end of the universe’s lifespan."
    h "Ambition, however, is not a rarity among the spacefaring generations of the various races that dot the cosmos, but culture and approach is."
    h "We were witness to another system that had similar megastructures and incredible engineering,..."
    h "but it was distinctive in that those aforementioned structures appeared to have been present for an extremely long period of time."
    scene bg megastructures_from_far2
    h "Most structures like space elevators and space bridges, which were once thought impossible to construct in our time, have been bleached by solar radiation and broken into fragments due to impacts from space junk."
    h "Somehow the planets had their orbits altered to the point where their orbits were in perfect alignment, allowing for bridges to be made to connect the planets together."
    h "I do not understand how such alignments could be maintained in the long term..."
    h "when considering that the impact of the gravitational pull of moons and collisions from non-planetary bodies could easily misalign the configuration."
    h "Our conjecture is that whoever created these space bridges destroyed the moons and any asteroids or comets which could interfere with the space bridges while using the raw materials to construct these bridges."
    h "This allowed for what I saw to exist and to last."
    h "We do not know for sure, since we were too far to see clearly whether this was the case, and there were not enough clues to confirm the negation or affirmation of this theory."
    h "I do not know what it took to do this, or how long, but what is clear is that it must have taken a great deal of creativity to resolve to construct such an unconventional thing."
    h "I imagine with each revolution, the planets traveled across the system like the hand of a clock, ticking away along a two dimensional plane even after their creators were long gone."
    h "I wondered what could have happened for a civilization to go dark as this one has."
    scene bg megastructures_from_far3
    h "Was it system level apocalypse, or were they spirited away?"
    h "As I darted away from this system, I saw, out in the cold reaches of space far from any star, a large solar system sized object that did not match anything I have seen previously."
    h "It was a large metallic object with corridors and grooves that zigzagged along its length, forming labyrinths of metal."
    h "Is this where everyone went?"
    h "Are they still there?"
    h "I wished I could get closer, but I was going in the opposite direction."
    h "It was clear that it was artificially made."
    h "There was no way that it could have been the product of one or two solar system's worth of raw material."
    h "No."
    h "This appeared too dense to be created from a single system."
    h "Whatever created this must have been capable of interstellar travel at the very least."
    h "What is it for?"
    h "I could only guess."
    h "In the end, I never figured out its purpose, or anything about it."
    h "The only thing I was sure of was that it was very old."
    h "As for how old, I cannot be sure, but it is possible that it is older than the human race."
    h "I could not tell what was happening within this object, but I did not see any activity from the distance I was viewing it at."
    h "We believe it was nothing more than ruins— the remains of a glorious empire."
    h "What happened here to lead to a civilization of such a level of advancement to disappear?"
    h "Did they destroy themselves in some event?"
    h "Famine is unlikely given their advanced nature."
    h "Did what happened to us happen to them?"
    h "War is possible."
    h "However, if there was a war, I do not know what that would look like, or what clues and remnants that would leave."
    h "What does an interstellar war look like exactly?"
    h "Is it loud and bombastic, or quiet and precise?"
    h "How is it fought?"
    h "Although I never found out the identity of this giant hunk of metal, I would learn well how interstellar wars are fought in the billions and trillions of years to come."
    scene bg first_contact
    h "By this point, it became apparent that not only was there life throughout the universe, but there were also many intelligent species, some of which managed to become space faring."
    h "The spacefaring civilizations, while they may have been few when we landed on the moon and walked on Mars, became more widespread in the eras and epochs afterwards, growing in number and diversity."
    h "Not only were we living in a galaxy teeming with life, but we were living in a galaxy that acted as the playground of many intelligent species."
    h "Each of these held their own culture, their own views on life, and approached their growth and spread in different ways."
    scene bg merchant_ships
    h "For those that could communicate with each other upon contact, I imagine they would open lines of trade and collaborate on large projects."
    h "There is no way to know for sure,..."
    h "but the patterns of movement, and interactions between spaceships that appeared to have designs originating from differing schools of thought..."
    h "indicated a level of interplay between multiple species on an interstellar level."
    h "Of course, this is merely speculation."
    h "When all one can do is peer through a hole in a wall, it is the only option left."
    h "Granted, it is always possible that multiple intelligent species grew together and originated on the same planet, and thus were able to coexist from the beginning."
    h "However, I have no way of determining the accuracy or probability of such a supposition."
    h "We could only extrapolate from the observations that we made based on past experience,..."
    h "and in an existence where all I could do was observe and theorize without consequence, my imagination led me down multiple interesting realms of possibilities."
    h "Sooner or later, I found myself questioning, given the nature of the large spans of distance between stars and systems..."
    h "and the way in which different systems travel throughout the galaxy, how can communication be handled effectively if it is limited to the speed of light?"
    h "I am willing to bet that these civilizations have mastered the quantum realm and may be capable of using small artificially created wormholes to send messages."
    scene bg telepathic_communication
    h "This would enable the flow of information to be instantaneous regardless of the distance and limitations imposed upon us by relativity."
    h "This means that communication between civilizations may actually be like our interactions over the internet:..."
    h "seemingly instant, overflowing with information, and effectively connecting multiple physical places in digital form."
    h "When the internet was made available to the average person, it allowed for a homogenizing of culture across the world where people could interact with each other regardless of the country that they were from."
    h "The main dividers seemed to be that of language and hardware."
    scene bg telepathic_communication2
    h "However, if a civilization has reached a sufficiently high level of advancement, then would it not be true that language would not be a barrier?"
    h "Similarly, differences in hardware or technology can easily be remedied by providing the appropriate information regarding how to manufacture and improve hardware to allow for new functionality."
    h "The phenomenon of homogenization may not be limited to the tools of communication, but also perhaps physical bodies."
    h "If one can upload their minds, then it could easily be the case that two different species may eventually develop to have the same bodies through biological engineering or cybernetic augmentation."
    h "After all, if you do not need to be burdened with the tools provided to you through evolution, then would it not be the case that the most optimal physical form would be chosen?"
    h "That would lead to the question of what is the most optimal form for a sentient being."
    h "As we've seen on Earth, there are certain forms that are better suited to some tasks than others."
    h "Therefore, it is unlikely that there is a physical form that would be the best at all tasks."
    h "What this means is, if a group has advanced far enough technologically, they may choose to have multiple bodies instead of one."
    h "It may be entirely possible for a single consciousness to control multiple bodies, or switch bodies in the way us humans may have changed clothes based on the occasion."
    h "Could an entire civilization consist of one consciousness?"
    h "The idea seems a bit too centralized to be manageable."
    h "Naturally, the changing of bodies may be a more intimate and personal action than changing clothes are, since the body can influence how the mind behaves and reacts to the outside world."
    h "Although the brain controls the actions of the body, it is also true that in many multicellular organisms with a neurological system,..."
    h "the chemical processes of the body can determine and influence the development and behavior of the brain."
    h "Therefore, I believe it is not out of the question for a choice of body to also be a statement on the choice of mindsets and behaviors one wishes to exhibit."
    h "It could very easily be what the fashion of intelligent species evolves into after they reach a spacefaring status."
    h "As might be expected, these speculations of homogeneity across civilizations and species are dependent upon finding common ground."
    scene bg populated_galaxy
    h "I envisioned a galaxy of species trading with one another, forming unions, and organizations."
    h "Like the United Nations, the European Union, NATO, and other large blocs,..."
    h "I fantasized of creatures from many planets organizing into councils, laying down infrastructure for interplanetary travel..."
    h "and allowing tourists from other civilizations onto their planets to leverage their interstellar reach."
    h "Outsiders would be won over by their soft power and technological prowess and, in the process, their influence and reach would grow even further."
    h "Political structures that might have existed on Earth may exist here in space on a larger scale with more complexity and nuance."
    h "There may be factions and divisions where certain species align themselves militarily with others."
    h "If there can be factions, perhaps there can be empires as well."
    h "What would governments of the future look like?"
    h "Generally speaking, in the earth's past, the larger a country was, the more difficult it was to govern."
    h "This was not only because of the physically larger land mass, but also because of the higher populations which typically contained more ethnicities and cultures."
    h "What about galactic empires and federations?"
    h "If humanity's history is anything to go by, it seems almost impossible to govern a significant portion of the galaxy when people are involved."
    h "Not only is it necessary to police crime on planets, but also it is necessary to prevent it in space."
    h "Space, as we all know is massive, and it is impossible to be everywhere at once."
    h "If someone wants to commit a crime, smuggle goods, or start a rebellion, it may be very difficult to stop it."
    h "The only way governance on an interstellar level may be possible is through the use of technology and decentralized rule."
    h "Even with the presence of wormhole based communication, it will take at least light years..."
    h "to send forces to suppress rebellions if those wormholes are microscopic and cannot be used to transmit large amounts of physical matter."
    h "Similarly, if there are any disasters or urgent events, the ability of a centralized government to respond is highly limited by its physical distance from the event that is occurring."
    h "This is assuming that these civilizations cannot break past the wall of relativity."
    h "I have not witnessed such a thing, and I have not seen any ships flying into wormholes or even seen a wormhole which can enable shortcuts through space."
    h "Based on what I have observed so far during my travels, there is infrastructure that allows for near light speed travel in the form of laser grids being placed in most systems that have been colonized."
    h "These seem to function as a sort of interstellar super highway that uses either light or gravity to propel and direct spaceships in the general direction of their destination."
    h "If faster than light travel was a possibility, then it is plausible that it was not something I would have been able to witness with my eyes even if it did exist."
    h "Will there eventually be a solution to such a problem?"
    h "Perhaps, but what is quite clear to me is that any large factions that emerge within the galaxy will not take a form that is similar to any empires that we have seen in the past."
    h "If they do, it is obvious that such empires will not last long."
    h "While I can see the possibility of civilizations and races tearing across systems, pillaging and scorching planets as they travel through the cosmos,..."
    h "actual governance and long term settlements that can last millions of years without conflict will require a level of ingenuity and maturity from all life that are its citizens."
    h "If the history of the human race is anything to go by, all empires eventually fall,..."
    h "and it is solely the competence of the leaders and the sentiment of the citizens which seems to determine whether the fall is graceful or bloody and violent."
    h "While I have not seen the expanse and reach of an interstellar civilization, what I have been able to bear witness to was the way in which more advanced civilizations would prey on others."
    h "It is said that there is always a bigger fish, but in space, size alone is not enough."
    h "Strategic savvy and technological superiority seems to be the deciding factor when it comes to battles in space."
    h "I have seen many ships become disabled from afar as their lights went out, and their propulsion zeroed out, leaving these large transport vessels floating in space on an uncontrolled trajectory."
    h "It seems that in space, destroying your enemies or your mark is taboo, or rather counterproductive."
    h "What seems to hold value are intact goods, prisoners, and ships."
    h "As a result, it seems that the preferred method of capturing prey is one that leaves them in one piece."
    h "The predation of less advanced civilizations is likely not only limited to space, but also extends into the realm of planetary invasions."
    h "Much like the conquistadors, I can fathom the concept of travelers from spacefaring groups finding uncolonized planets and claiming these planets for themselves to use as they please."
    h "I estimate that when mankind was just beginning to escape Earth's gravity, such civilizations were few, making the first groups capable of interstellar travel the ones which carried out such invasions."
    h "This must have left civilizations that had yet to make first contact with the decision of whether to advertise their position to potential life in the universe, or to go radio silent."
    scene bg dead_universe
    h "Indeed, there must have been some planets that managed to hold their own against the invaders for some time, but there also must have been others that have predicted the dangers of communicating on full blast."
    h "Later on, as more planets became colonized, we likely begin to see this reach a ceiling as races and civilizations arrived upon the cosmic borders they formalized for their interstellar territories."
    h "If this was the case, then the increasingly ambitious nature of many of the inventions I saw acted as plausible evidence."
    h "Things I would have originally thought impossible or beyond the realm of intelligent life began to fill the skies."
    h "From bright systems powered by Dyson spheres and artificial moons to colonies and settlements on the edge of black holes,..."
    h "the ingenuity of intelligent life allowed for those who lived to use the power of stars and black holes to transcend space and time and manipulate the universe to their will."
    h "At the same time, in the later stages of the universe before the stars went dark, I saw the aftermath of space based life."
    h "These organisms fed off of the space dust and whatever was available in space to reproduce and fill the empty space with biological matter."
    h "Like the plants that filled the empty ocean floors and colored the earth green, these extremophiles (or perhaps astrophiles) were capable of surviving in a vacuum in a range of temperatures."
    h "If it were not for the expansion of the universe, I believe these creatures would have spread through the cosmos like a virus and supplanted the status quo."
    h "Fortunately, they did not, and I could enjoy the fruits of advanced civilizations without limit till the end."
    h "The end, if it could be called that, was gradual."
    scene bg dying_civilizations
    h "It was a slow process that took place over trillions of years and was a long period of turbulence, uncertainty, and a slow dying."
    h "It was like watching a sick, old man with labored breathing fight to live when a quick, merciful end might have been for the best."
    h "As time passed, the civilizations that kept pace on my journey began to drop away."
    scene bg dying_civilizations2
    h "Some of them were wiped out in wars where they fought over the empty region of space that I occupied."
    h "These wars were not dissimilar to watching ants and insects fight."
    scene bg intergalactic_wars
    h "It was, from a distance, like watching large armies in intricate geometrical shapes change configuration over and over until one side was no longer left."
    h "If I had to liken it to something, it was like watching a game of Go."
    h "However, where Go might be played by two players on a flat board with a grid, this was a game with far more complexity."
    h "It was a game with trillions or even quadrillions of players, an endless, continuous grid, and it took place in at least three dimensions."
    h "The strategic foresight on each and every spaceship, on each army, was something that would make the most intelligent human seem as smart as a rock..."
    h "and I imagine the toll was something that would make the worst of humanity’s past atrocities against their fellow man seem peaceful or merciful in comparison."
    scene bg intergalactic_wars2
    h "Then there were the eccentric."
    h "Some of those who were not wiped out in war wasted their resources building strange, functionless structures wherever I went as though they were planting flags."
    h "These were beautiful and intricate pieces that seemed to have artistic value, but art is a very subjective thing."
    h "It had the sophistication of Roman architecture while at the same time an organic and spontaneous feeling like a Jackson Pollock painting."
    h "Stylistically, it seemed to transcend themes and messages that we were familiar with."
    h "Whether something was lost in translation, or it was simply the difference between an ant and a God, I understood nothing other than that I should be in awe."
    h "Whenever light shown upon these designs, I could remember that I was not alone, and have a sense of calm that I had not felt since the time I was born."
    h "It was a feeling of congeniality, of adoration, of love."
    h "I did not comprehend what compelled these beings to chase after me, but I was thankful."
    h "I was thankful that they did and that they stayed with me for all these years, sacrificing their livelihoods."
    scene bg dead_universe2
    h "This too, like all good things, had to end."
    h "The last that were with me lost pace, slowing down and taking distance with every century and millennia."
    h "They were losing ground against the current of time."
    h "Eventually, they were so far away I could not see them."
    h "I recall being in the dark and hoping that they were still there, just past my range of vision."
    h "However, I knew at some point that they would run out of energy and disappear into the darkness never to be seen again."
    h "The worship of the greatness of existence acts as a reminder of its eventual close."
    h "As the stars died, and the universe returned to blackness, I understood then that the luxuries I enjoyed up to that point would never return."
    h "My universe was dead, and what was left of it was a corpse that would rot away until nothing was left."

    menu:
        "Try to flex phantom limb":
            jump P2C7
        "Do nothing":
            jump P2C7
