# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define h = Character("Humanity")

image bg alone_in_a_crowded_society = "P2C7/bg P2C7 Being alone in a crowded society.png"
image bg alone_in_a_crowded_society2 = "P2C7/bg P2C7 Being alone in a crowded society 2.png"
image bg alone_in_a_crowded_society3 = "P2C7/bg P2C7 Being alone in a crowded society 3.png"
image bg greed_envy_gluttony = "P2C7/bg P2C7 Greed, envy, and gluttony leading to the suffering of the human race.png"
image bg pride_of_civilization = "P2C7/bg P2C7 The pride of human civilization becoming its downfall.png"
image bg pride_of_civilization2 = "P2C7/bg P2C7 The pride of human civilization becoming its downfall 2.png"
image bg alone_in_a_dying_universe = "P2C7/bg P2C7 Alone in a dying universe where everyone else has faded away and only you are left.png"
image bg calling_out_desperately = "P2C7/bg P2C7 Calling out desperately into an empty universe with noone or anything left to reply back or even leave an echo in a dark and abstract style.png"
image bg our_ancestors = "P2C7/bg P2C7 Our ancestors learned the sciences and the maths so that we could supposedly learn the arts. Their ancestors fought wars so that their descendants cou.png"
image bg our_ancestors2 = "P2C7/bg P2C7 Our ancestors learned the sciences and the maths so that we could supposedly learn the arts. Their ancestors fought wars so that their descendants cou 2.png"
image bg repeating_thoughts = "P2C7/bg P2C7 Sometimes thoughts repeat themselves, but occasionally a unique idea can form under unique conditions. I wonder, do you need to be intelligent or even.png"
image bg repeating_thoughts2 = "P2C7/bg P2C7 Sometimes thoughts repeat themselves, but occasionally a unique idea can form under unique conditions. I wonder, do you need to be intelligent or even 2.png"

label P2C7:
    show screen centeredbox("{size=+10}Chapter 13: Stranded{/size}")
    pause
    hide screen centeredbox

    scene bg alone_in_a_crowded_society
    h "In a sense, we are all born alone, live alone, and die alone."
    h "This is the predicament of all life."
    h "The presence of others is merely a distraction from this fact."
    scene bg alone_in_a_crowded_society2
    h "There is nothing here but me."
    h "The thoughts I think are mine."
    h "You standing there before me is only of significance if I notice you and acknowledge your presence."
    h "Otherwise, your existence is diminished."
    h "If you were out of my sight, and I did not hear you or notice your influence on my world, you would effectively not exist to me for that moment."
    scene bg alone_in_a_crowded_society3
    h "We are all isolated from one another."
    h "This is a double edged sword."
    h "On one hand, you have a sense of privacy, and by keeping yourself separated from others, you can generate a unique identity."
    h "This identity is one that can only be created by oneself, but can be influenced by others."
    h "The higher the influence of others, the less of a unique identity you will have."
    h "This is the price that needs to be paid to recognize oneself as an individual with their own set of distinguishing qualities."
    h "This was true in the days we were mortals."
    h "It is only more poignant now, just in a somewhat twisted form."
    h "Other planets have had civilizations that rose and fell, but were never cursed or never observed to be cursed."
    h "These civilizations never understood me."
    h "I only understood them at a surface level."
    h "We were as separate and distant as strangers passing by in a crowded street."
    h "Although we never truly knew one another, I was sorry to see them go."
    h "It was like those moments where the bar or café that I frequented eventually became another home."
    h "I was a regular and at some point, when I was not lost in my drink, I noticed the other regulars."
    h "Despite not speaking or knowing anything about them, the days that they were not there were the days that felt off."
    h "I would overhear their conversations, and they would overhear mine."
    h "I would gradually understand their usual schedules and could predict when they would enter through the front door."
    h "I would go in, and see the same bartender or barista, and at some point, they would remember my name and my usual orders."
    h "Then, one day, I would come in like I usually did, and they were simply gone, and it was not for a single day."
    h "Sometimes it would be death, other times, life takes them to other places."
    scene bg calling_out_desperately
    h "I could call out “Come back,” but they were already gone."
    h "Though my memories of them will remain, if we were to meet again, it would not be through the usual means."
    h "Their ends are likely different from my end."
    h "They met their deaths in ways that seemed to be either under their control or the consequences of their actions."
    h "Whether they died with a bullet to the head, cancer, or simply shot themselves in the foot and bled out, all can be traced back to their actions in some way."
    h "In the midst of the growing scarcity within the universe, those who met their ends found troubling ways to go about it."
    h "There were those that seemed to choose to destroy themselves in a form of self-imposed genocide."
    h "I witnessed one planet do it, and later saw the aftermath on the far reaches of the domain of their sovereign rule."
    h "Rather than a single leader deciding and wiping out all life, each planet belonging to this civilization destroyed itself with weapons of mass destruction."
    h "They could clearly go on for millennia afterwards, but they felt compelled to end it then and there, leaving working machinery that did not rot and never became idle to toil for the rest of eternity while their corpses decomposed."
    h "It could have been the case that they realized that their end could have been one of the most noble of missions."
    h "It could have been one of the greatest sacrifices."
    h "Alternatively, it could have merely been the only escape."
    h "It could have been a mercy for those who survived: feed off my dead husk so that at least you may have a chance to live and tell the tales of our glory."
    h "The others who fought and fought to the dying end seemed to be the ones to either achieve immortality and escape, or the first to die."
    h "As though realizing that there was a choice between endless struggle and finding a solution..."
    h "at the risk of ending an empire, they chose the route that ventured to thrash against the forces of nature before they too would join the darkness."
    h "In doing so, they expended resources, lives, and quenched their suns, squeezing out every drop of energy they could..."
    h "in the hopes that they could reach the finish line of Samsara and become reborn in another time or another reality where they would no longer need to suffer."
    h "It was not to be, and they too would vanish."
    h "First it would be one planet, then the system, each bastion of life going dark."
    h "One at a time, like flames being quietly extinguished."
    scene bg alone_in_a_dying_universe
    h "Each planet died alone."
    h "Each individual in that empire died in their own unique way, but they died nonetheless."
    h "Was it worth it?"
    h "To die in that way?"
    h "Is it worth it to continue to live in misery and pass long after nothing is left?"
    h "Only the dead can tell, and they're long gone."
    h "The ones who are left will either leave this universe for greener pastures or will meet similar ends."
    h "All that is left here are ashes, voids, and nothing on the horizon."
    h "You can choose your destination, but you can't see it."
    h "Discovery, exploration, conquest: pointless when all the fields you find are barren."
    h "Just as my life is my own, so too is my experience."
    h "We are alone in our suffering."
    h "There are no others."
    h "I am the only one doomed to wander the universe for all eternity."
    h "This is what I believe."
    h "If there were others, I have not seen them."
    h "If there were others, even if I spend the remainder of the universe watching for them, it is doubtful that I would ever find them."
    h "In the darkness, they may effectively have never existed."
    h "What if there was no darkness?"
    h "What if I could see everything without needing to strain myself?"
    h "Even then, it is unlikely that I would ever find them."
    h "Each galaxy is vast."
    h "The observable universe is even more vast."
    h "This observable universe which consists of clusters, superclusters, and more has a scale that is beyond human understanding."
    h "You could see a number describing its size and not fully understand it due to lacking the context."
    h "It is massive."
    h "However, this is a meager speck within the unobservable universe that lay beyond all light that had a chance to travel before me."
    h "This unobservable universe and everything inside of it is expanding."
    h "It is expanding so rapidly that the remnants of massive superclusters become measly islands within the spaces between, oases within a hostile reality."
    h "You may venture out into the unknown at your own discretion, but unless you can effortlessly traverse distances..."
    h "on a scale that dwarfs galaxies, clusters, and the former observable universe, then you will simply be setting out to die a meaningless demise with little hope of rescue."
    h "Indeed, if there were others just like me, they would be trapped within their predetermined paths, blindly stumbling through an empty reality."
    h "A meeting is never meant to be."
    h "This leaves the poor souls I took with me."
    h "Like all things, I had taken them for granted until the day they were gone despite understanding their eventual fate."
    h "However, unlike the life that proliferated throughout the cosmos, these were special."
    h "They were mine."
    h "They were there for me."
    h "If it was not for me, they could have spent their finite time in a more meaningful way."
    h "For that, I feel deeply remorseful."
    h "I had nothing to offer them, and yet they stayed by my side."
    h "What were they thinking?"
    h "Why follow me?"
    h "I asked and asked, but my voice never reached them."
    h "When I first made their acquaintance, I noticed that they had receiver-shaped structures like antennae directed towards me."
    h "I asked myself whether they were listening."
    h "Maybe they were trying to hear me, but I was simply not loud enough."
    h "It could have been that they did hear me, but they simply did not understand."
    h "If they did, why did they not send something back?"
    h "Why did we not communicate?"
    h "Or was it simply that while they could communicate, I was not able to hear them?"
    h "The endless spiral of blame that I fall within never seems to stop dragging me deeper into the abyss of incomprehension."
    h "I did not understand them, their purpose, or who they were."
    h "They did not understand me, otherwise we should have been able to communicate."
    h "It was a lost opportunity."
    h "I felt for them."
    h "They remember a time when the universe was more abundant."
    h "I made them waste their moments of youth and follow me into these times of desolation, and all I could do was watch."
    h "It was like watching a sick patient, like someone you love passing away, wasting slowly."
    h "You would want to do everything, but you don't know what you should do, or even what you can do."
    h "Their fate is out of your hands."
    h "Is this what it truly means to be alone?"
    h "To have nothing but your own thoughts to hold you close?"
    h "At times it does not sound too bad."
    h "As humans, we did not always need others to live."
    h "Although our identities as social creatures have been coded into our genes, there has been value in each and every one of us being able to function as individuals who are capable of being self-reliant when the time calls for it."
    h "I can scarcely recall the feel of another person, but I yearn for it."
    h "I just wish to be held in another’s arms, to be separate from others with my own thoughts but still together in spirit."
    h "The tactile sensation of another person’s skin, the emanation of warmth radiating through human contact."
    h "The understanding that we are separate individuals brought together is one that I cannot stop longing for."
    h "You do not need others to live, and yet it hurts to be without them, like holding your heart over a vat of liquid nitrogen and feeling it gradually freeze into a hard mass of flesh that can easily shatter when dropped."
    scene bg pride_of_civilization
    h "Simultaneously, the presence of others can be like holding your heart over an open flame and feeling it slowly turn to cinders like your personality is being eroded away bit by bit."
    h "Others can be hurtful and unforgiving."
    h "They can insult you, reject you, and deny you of any dignity at a moment's notice."
    h "To be able to trust, we must have relationships that are built on a foundation of trust."
    h "However, trust is difficult to build and easy to destroy."
    h "Often, backstabbing and treachery have even been rewarded and have been a strategic and pragmatic choice."
    h "One moment you are a friend, and the next, you are a stepping stone."
    scene bg pride_of_civilization2
    h "The whims of humans are fickle, and betrayal and shame can be directed towards you without warning."
    h "This is the nature of human relationships."
    h "There is the experience of being cheated and the experience of cheating."
    h "Selfishness and ego dominate our actions."
    h "We have lived lives of much pride, but also much shame, and that made us flawed creatures."
    h "The identities we built for ourselves were unfortunately dependent upon the opinions of others."
    h "By doing so, our identities become an extension of society and those around us rather than an extension of ourselves."
    h "This leaves those who are unable to fit in a dire predicament."
    h "The pain of not fitting in is one that imprints itself as trauma and can last a lifetime."
    h "It can build and build to destructive effect."
    h "Then there are those of us who fit in, but understand that they have nothing in common with their fellow man."
    h "They are there, mixed within the crowds, but they are not the same as everyone else."
    h "They are an outsider wearing one face in public and wearing another in private."
    h "They do this not to deceive, but to survive."
    h "Yes, if you are different, you become the nail that sticks out only to be hammered down."
    h "It is easier to live a safe life than a daring one."
    h "It is better to exhibit the qualities that society values rather than qualities that may result in an objectively more fulfilling livelihood."
    h "We have no choice but to do this."
    h "If not, we are recognized as worthless, as the scum of society."
    h "They become the abandoned goods lining the streets who need to be thrown away."
    h "If you cannot exhibit your value, you only exhibit the reasoning for your disposal."
    h "As a result, we all live lives we do not wish to."
    h "We turn our backs on who we are and who we think we are meant to be and give up on our dreams."
    scene bg our_ancestors
    h "Our ancestors learned the sciences and the maths so that we could supposedly learn the arts."
    h "Their ancestors fought wars so that their descendants could learn the sciences."
    h "This was how it was meant to be."
    h "Each generation was to leave a better life for their descendants."
    h "However, the wars never stopped."
    h "The ties between generations degraded."
    scene bg our_ancestors2
    h "Society never advanced, and people never grew beyond the practice of exhibiting their value as individuals."
    h "The great things we were meant to do were never in the plans."
    h "No, we were only cattle to be slaughtered, walking the paths we were told to walk."
    h "Indeed, if it were not for others, we may have lived the lives we wanted."
    h "In the past, this may not have been the disadvantage we thought it was, because our actions were contributing to our survival."
    h "However, in a time of plenty, in a time when scarcity was no more, we continued regardless of how unreasonable."
    h "Yes, whenever we fixed a problem, we would introduce another in its place."
    h "It was all systems of control that continued endlessly, depriving us of ourselves, and turning relationships into feeding frenzies..."
    h "where everyone became emotional vultures preying on one another when they were at their most vulnerable."
    h "We were never meant to build utopias where people can coexist peacefully."
    h "We were not designed for that."
    h "We were meant to survive the forces of nature."
    h "Anything beyond that is simply extraneous."
    h "All we were meant to do was to handle any obstacle that came our way, get a leg up on any and all competition, and leave behind offspring that would be doomed to do the same thing."
    h "Even if we built utopias, how long can such a thing stay intact?"
    h "All civilizations rise and fall."
    scene bg greed_envy_gluttony
    h "People grow greedy, and the cycle of misery continues."
    h "The utopias that celebrate our individuality rather than use our individual nature as a way to force responsibilities that were no longer needed would never last."
    h "We can say that one day we could have lived in a time when others would not have stomped on our creativity and imposed their views on our identities, race, sexualities and backgrounds."
    h "We could say that we could have grown into agreeable individuals even with the presence of others."
    h "However, one does not discover the evils of the world by living in isolation."
    h "Love could be a silver lining."
    h "Love, especially that which is unconditional, can be a support in the hardest of times."
    h "But whether there truly is such a thing as unconditional love is questionable."
    h "Conversely, it could also be considered to be foolishness— as trust is self-imposed weakness and vulnerability."
    h "You can love yourself, but that has a distinctive difference from the love of others."
    h "The feeling of appreciation from others, the need to depend on one another can provide a purpose where there was none."
    h "But what if that was only a smokescreen?"
    h "What if that was only meant to be a distraction for simple-minded people like us so that we do not realize that we are more alone than we realize?"
    h "It is a disheartening thought that forms in the absence of absolute confidence."
    h "It is also a thought that has a stronger empirical basis than a naive notion that love can conquer all."
    h "There is much of me that wishes not to think of it, and oftentimes, I do not."
    h "It is also a topic that is very rarely broached in conversation."
    h "Ah! There is another silver lining: conversation and interplay."
    h "The marriage of minds in the exploration of ideas: collaboration, cooperation, confluence, and maybe even a shared mission."
    h "The ability to share your thoughts and incorporate ideas completely alien from anything you may consider yourself."
    h "It could be argued that ideas are living organisms themselves."
    h "Like us, they too grow and adapt to their environments."
    h "They change based on advancements in topics or can wither and die as a topic is changed or another idea gains a greater hold on the attention of individuals."
    h "These thoughts and figments of our imagination are also, like other humans, our offspring."
    h "If thoughts were individuals, then they obey laws of natural selection as well."
    h "They can reproduce through the collaboration of two human minds, or can be brainstormed by a single person: sexual and asexual reproduction."
    h "However, without us, they would simply wither away."
    h "I wonder, how many ideas are out there lost to the march of time?"
    h "How many ideas are out there that we have yet to think of?"
    h "Surely it must be infinite."
    scene bg repeating_thoughts
    h "Sometimes thoughts repeat themselves, but occasionally a unique idea can form under unique conditions."
    h "I wonder, do you need to be intelligent or even sentient to form a thought?"
    h "Is it possible for an inanimate stone or even the universe to have thoughts of the future, to form ideas?"
    h "Perhaps their manifestation of a thought is in the physical form."
    h "The decision to form planets, the decision to expand."
    h "These all follow laws, but there is a certain level of randomness, of stochasticity, mixed into the process."
    h "What happens is predictable to some extent, but not necessarily predetermined."
    h "There is still the opportunity for interplay."
    h "Perhaps, we too are thoughts and ideas dreamt up by the universe—memes born out of a being that operates on a far greater timescale."
    h "Maybe we were simply those in a long line of thoughts and ideas that were manifested by this creature."
    h "It could have been that in the moments after the big bang, there was life completely alien to us, based on sub-atomic particles and energy..."
    h "instead of molecules, which lived and died on the matter of nanoseconds that may have had simple thoughts."
    h "I wonder, if those creatures lived in our time, would they have found it to be an unbearable slog as we find this time to be to us?"
    scene bg repeating_thoughts2
    h "To find out, could we ask the universe?"
    h "Maybe, but would the universe know the answer or be aware of it?"
    h "Like we are unaware of the activities and actions of our cells, we could simply be too insignificant to even be considered a thought."
    h "We might just be like a neural activation, the beginnings of a thought, but not quite the end product."
    h "We may just be a process in a long line of processes."
    h "At the beginning, the thoughts of the universe may have been simple: grow, expand, consume, explore."
    h "As it grew more mature, its thoughts grew in complexity and became more abstract: form, gather, think."
    h "Now, what is it thinking?"
    h "Are its thoughts more like that of an Alzheimer’s patient with vast distances and vague memories of what it once was, or is there more to come?"
    h "Is there a complexity within this emptiness that is beyond human understanding?"
    h "Is there something wonderful hidden within the quadrillions and quintillion years to come?"
    h "Will there be conversations with other realities and universes to create new ones?"
    h "Is there a way to find out?"
    h "At this time, in this moment, the only one I can ask is the universe itself."
    h "If the universe could speak back, maybe I would not feel so alone."
    h " Maybe we can engage in conversation, create new ideas, and grow into something new and different."
    h "If the universe could speak back, maybe it would be my friend."
    h "Maybe it already is, and I just have not realized."

    menu:
        "Try to flex phantom limb":
            jump P2C8
        "Do nothing":
            jump P2C8