# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define h = Character("Humanity")
define voice1 = Character("A Voice Among Billions")
define a_voice = Character("Another Voice Among Billions")
define meme1 = Character("Meme")
define meme2 = Character("Another Meme")
define meme3 = Character("A Meme About the Hard Times")
define meme4 = Character("Chad Meme")

image bg reality_passing_by = "P3C2/bg P3C2 Reality and the universe passing by you at a disorienting speed beyond the standard passage of time.png"
image bg reality_passing_by2 = "P3C2/bg P3C2 Reality and the universe passing by you at a disorienting speed beyond the standard passage of time 2.png"
image bg reality_passing_by3 = "P3C2/bg P3C2 Reality and the universe passing by you at a disorienting speed beyond the standard passage of time 3.png"
image bg reality_passing_by4 = "P3C2/bg P3C2 Reality and the universe passing by you at a disorienting speed beyond the standard passage of time 4.png"
image bg trillions_of_possibilities = "P3C2/bg P3C2 Trillions upon trillions of possibilities abstract, but also photorealistic.png"
image bg trillions_of_possibilities2 = "P3C2/bg P3C2 Trillions upon trillions of possibilities abstract, but also photorealistic 2.png"
image bg trillions_of_possibilities3 = "P3C2/bg P3C2 Trillions upon trillions of possibilities abstract, but also photorealistic 3.png"
image bg trillions_of_possibilities4 = "P3C2/bg P3C2 Trillions upon trillions of possibilities abstract, but also photorealistic 4.png"
image bg alcoholic_supercluster = "P3C2/bg P3C2 An alcoholic supercluster.png"
image bg pinkish_silhouette = "P3C2/bg P3C2 a pinkish silhouette that changes colors based on mood in the vacuum of space.png"
image bg pinkish_silhouette2 = "P3C2/bg P3C2 a pinkish silhouette that changes colors based on mood in the vacuum of space 2.png"


label P3C2:
    scene bg reality_passing_by

    show screen centeredbox("{size=+10}Chapter 16: The Voices in Our Head{/size}")
    pause
    hide screen centeredbox    

    h "Enough time has passed to the point that we are stunned that my mind has not already turned to mush like a form of synaptic retrogenesis."
    h "Humans have an intellect that barely allows them to process a century’s worth of information, but this is far beyond that."
    h "Perhaps it had already become mush from the moment we became one being."
    h "The line between the sane and the insane is thin, indistinct, and vague."
    scene bg reality_passing_by2
    h "Maybe we were all certain levels of insane, and together we created this complete mess of a person."
    h "Regardless, I have managed to maintain some semblance of human thought that can be described with words."
    h "As to how long that will be the status quo is questionable, but I think that I am at my breaking point."
    h "The voices in my head don’t stop, and I can no longer trace them back to the original personality that they belong to."
    h "They just echo back and forth, talking about everything from the mundane to the freakish."
    h "From one conversation between two disembodied voices discussing the weather and the rate of inflation to conversations about tumors..."
    h "and how to control groups of people within a cult, the topics are erratic and lack logical ties."
    h "It is as though I am being unwound into multiple people who are no longer who they used to be."
    h "Sometimes the voices are loud, sometimes they are soft, but they are very rarely silent."
    h "I can usually hear them, and whenever I think they are about to fade into the background, they come back."
    scene bg reality_passing_by3
    h "It is as though the source of the voices can read my mind."
    h "Of course they can."
    h "They are me."
    voice1 "Is that an object approaching?"
    voice1 "What was that flash of light?"
    voice1 "I can’t be the only one seeing that right?"
    h "It is only through the well trained mental fortitude that I built through the eras and a certain level of desensitization that I can filter these voices out."
    h "However, the moment I relax, the noise begins to come back."
    h "True relief, it seems, is no longer a luxury that I can afford."
    h "When I direct my attention outwards, I find that there is little I can gather to anchor myself to reality."
    scene bg reality_passing_by4
    h "There is no light, no sound, and I have lost all sense of the speed that I am traveling at."
    h "When everything is pitch black, it is as though you have your eyes closed."
    h "However, when you have your eyes closed, you have the option of opening them."
    h "In our case, I am deprived of all sensory details, as though I was in a sensory deprivation tank for unimaginable periods of time until all my nerves have degenerated and everything has gone numb."
    h "This state of nothingness has gone on long enough that I can no longer tell if anything we experienced in the past has actually happened,..."
    h "or if I am simply remembering events, real and imagined, to cope with the current reality."
    h "If I take a method of deductive inference, then we could take the clues and signals that I can observe and use them to extrapolate to the past to learn how I arrived at where I am."
    h "However, there are no clues here."
    h "There are no signals, and no breadcrumbs."
    h "Only me."
    h "The trail has gone cold eons ago."
    h "Now, all I am is a disembodied consciousness that effectively does not even exist and interact with an environment."
    h "I am like those artificial intelligences and simulations that existed within the world of circuits and transistors."
    h "I may as well be a brain in a vat of fluid."
    h "There is only some initial input in the form of memories."
    h "The rest is something we need to figure out on our own."
    h "It is interesting how in the past I remember, I felt so sure that I lived many lives as different people and that the universe we lived in was real."
    h "The limited senses I had acted as the foundations for us to build our sense of confidence."
    h "The times when I felt as though I was experiencing reality felt so short compared to the eternity of nothing that followed."
    h "That feeling, however warped it may be, has some basis in truth as the time of stars is over and will never return."
    h "Despite having an imperfect perception of the world, we placed so much importance on our senses, and now that they are gone, we have nothing to base our perception of reality upon."
    h "We can say that we think and therefore we are, but the very nature of our existence is a mystery."
    h "Do we take our memories at face value to represent what the past was, or do we scrutinize them to find holes in their construction?"
    h "If we choose the latter, then how can we distinguish between memories that are inconsistent with reality, and memories that are flawed due to the passage of time..."
    h "which numbs the sharpest of pains and relegates each past event into a homogenous blur?"
    h "The tools of reasoning we have at our disposal are deteriorating, and as time passes, our state of mind robs us of our ability to reason and cope with our reality."
    h "This was true when we supposedly walked the earth, but it is truer now."
    voice1 "How bad could letting go be?"
    voice1 "If fighting against the current is so hard, then why not simply lose our grip on reality?"
    voice1 "Reality does not matter anymore."
    voice1 "Why cling to it?"
    h "The scientific method, of which we can use to derive answers about reality, has turned its back on us."
    h "We no longer live in a place where there are independent variables and dependent variables."
    h "Here, there are no variables except us."
    h "We are the one and only."
    h "We can change how we think, but outside of that, there is nothing left to act upon even if we could act upon it."
    h "Free will means nothing if there is nothing to act on."
    h "We are now living statues, petrified in place."
    h "Our eyes are covered in stone lids, and we cannot open them."
    h "The phantom limbs we so desperately worked to move and feel are now pointless."
    h "The time we wasted in search of that which was never there will never come back, and all the progress made is meaningless in the face of a universe we cannot influence."
    h "The voices tell me it will be okay."
    h "Sometimes they urge me on, and other times, they stomp my aspirations into the ground in a bout of emotional whiplash."
    h "It does not matter whether things will be okay or whether everything is hopeless."
    h "We lose the moment we take the statements at face value."
    h "However, in this lonely place with no one else around, these voices are the only other thing out here that I can treat as someone else."
    h "They are the wall I can bounce my ideas off of."
    h "That is an opportunity that seems all too enticing at times."
    h "Perhaps there will come a day when I let go and begin to engage in conversation with these voices."
    h "However, that day is not today."
    h "I am still aware of who we are and who we are not and, the moment we take the plunge, that distinction ceases to be as apparent as it is now."
    h "In a world of nothing, the smallest crumb appears appetizing."
    h "Despite this, whether I like it or not, I have managed to create a foundation of self-control."
    h "Rather, it is a mindset of asceticism that comes not from limiting myself, but instead from being heavily deprived."
    h "When I know that nothing I do will fulfill my desires or needs, the very nature of taking actions and breaking discipline is an impossibility."
    h "I have nothing, and I will gain nothing."
    h "Whether this situation is good or bad is completely relative, and completely up to me."
    h "I learned this lesson well back when there was still light in this universe, and over time I retreated into the depths of my mind."
    h "My sense of self is only vaguely human now."
    h "It has become more of an idea of a person rather than a person with identifiable features."
    h "I have become a shadow."
    h "The real me is somewhere else."
    h "Maybe the real me can be found, but with each second that passes, that person slips out of our grasp."
    h "What we are now is an amalgamation of qualities that transcend the physical."
    scene bg pinkish_silhouette
    h "Whenever I picture myself, I do not see a humanoid bipedal body, but rather a pinkish silhouette that changes colors based on my mood."
    h "When I become angry, it becomes pointed and jagged with rough edges."
    h "When I become calm, it turns fluid and amorphous, like water accumulating into a human shaped puddle."
    h "It is as though I am an elemental force of nature."
    h "Sometimes, I am a discrete particle."
    h "Other times, I am a fluctuating wave."
    scene bg pinkish_silhouette2
    h "With such a mindset, the qualities of cultural exchange and social transactions mutate as well."
    h "Where one could base their identity off of a hometown or location on the earth which was complete with its own local cuisine, architecture, way of life, language, and practices, such identities no longer have any significance."
    h "I am no longer a child in the Chinese countryside, or a businessman in a bustling American city with skyscrapers running along the horizon."
    h "I am now whatever I choose to be."
    h "I have lived many lives, and took on the roles of many people."
    h "I have thoroughly traced the possible futures of each person, the interactions they might have had with other parts of me, and how they may have chosen to live."
    h "In the process, I have memories of lives I have only imagined outnumbering the lives that I have actually lived."
    scene bg trillions_of_possibilities
    h "This is trillions upon trillions of possibilities."
    h "Furthermore, these lives are not limited to those lived on Earth or even in this universe."
    h "Can a human mind handle all of that?"
    h "I do not know."
    h "All I know is that I had enough time to become lost within the sea of information that I generated by myself."
    h "Within these virtual worlds manufactured inside my head, the lives of humans gradually became boring."
    h "It was not as though I completely abandoned living such lives in my daydreams, but it was more that the humanity within these lives were gradually becoming unrelatable."
    h "The human part of me kept returning to these moments that never happened while the intellectual within me grew to take on its own personality that abstracted away from the things that made us human."
    h "I would rush to the climax, skip the buildup, and edit out the boring parts."
    h "My sense of humor had already been somewhat twisted and warped towards the avant-garde due to the vibrant meme culture of the internet era, but humor in this day and age has become something else."
    h "Vast expanses of empty space have become personified."
    h "They take on personalities and play a role in my jokes."
    scene bg alcoholic_supercluster
    meme1 "Hello, I used to be a supercluster."
    meme1 "After becoming an alcoholic, I became divorced from my universe and now pay alimony to a quasar."
    meme1 "Look at how my standards have dropped."
    meme2 "Here is a disembodied head whose body is gradually being formed out of stardust."
    meme2 "Be careful."
    meme2 "If you form a star, you'll stand out of the crowd."
    meme3 "Woe is me."
    meme3 "I don't even have two protons to rub together."
    meme3 "My boss is rolling in antimatter, but for some reason, I don't get a raise."
    meme4 "Random variables be like: I don't know what I am."
    meme4 "Meanwhile confident chad Gaussian distributions be like: if it wasn't for me being responsible for the central limit theorem, you peasants would have no complexity and only entropy."
    scene bg trillions_of_possibilities2
    h "The ones with strange sounds are among the best."
    h "Despite farts as a facet of humor being used in jokes in the 21st century, for some reason, variations of this sound simply did not seem to go away."
    h "Even today, a random fart here or there can breathe life into a boring joke that fell flat on its face."
    h "Then there are the ones that are completely inhuman."
    h "Beeps synchronized to sorting algorithms, squeaky noises whenever a supernova could be seen in the distance back when they still happened, a snoring black hole."
    h "While many of these are quite bizarre, they still have something about them that appear to be somewhat relatable to a human."
    h "I suppose that is what makes them humorous."
    h "There is something to ground them within my mind."
    h "The best jokes seem to be the ones that are meta and complex with self-references and high level connections between ideas and concepts that have nothing to do with each other on a surface level."
    h "Such inside jokes can make mundane, everyday things humorous because they implicate something deeper that is the source of the joke."
    h "Similar to hearing a random default Android notification out of the blue, the simple parts of everyday life have transformed..."
    h "into the centerpieces of jokes that are difficult to explain, but do not seem to lose their freshness."
    h "Over the years, while the jokes become more and more unrecognizable to the humans of the past, they still manage to tie in some aspect of the universe around us."
    h "Although we have been running out of material as everything gradually went dark, humor, which has been one of the only coping mechanisms we had left, never went away."
    h "Even now, we find a way around the obstacles placed in front of us by diving deep into our memories..."
    h "and transforming them into their many permutations like a machine learning algorithm training itself on the same data over and over again and increasing its training data through clever mathematical tricks."
    scene bg trillions_of_possibilities3
    h "Our humor no longer draws from what has happened, but also what is possible, what is impossible, and everything in between."
    h "Of course, when it comes to memes and jokes, part of the appeal is being able to share them with others."
    h "To enjoy such an experience, we have effectively created a social network of one person: me."
    h "It is not so much an interconnected web, but rather a common space that can be visited by any part of myself as we please."
    h "We created a user interface within our imagination, not unlike the social networks of the past, where we can generate profiles which represent the parts of us we want to show to others."
    h "It is a superficial gesture seeing as we are all one person and we know fully well what each other is thinking."
    h "Despite this, we consciously participate in this charade, to wring out whatever joy we can by carrying out this exercise."
    h "We construct multiple chat rooms and forums within a multiverse in which we can interact with each other and share the jokes we have."
    h "We have back and forth conversations where we try to outdo what was previously posted."
    h "One image gets downloaded, photoshopped, and then re-uploaded to try to improve upon what came before."
    h "Before long, we have forgotten what the original looked like and all our attention is focused on the surreal creation that shows as most recent in our message thread."
    h "These conversations I have with myself initially felt like a futile struggle against my loneliness,..."
    h "but eventually these different parts of my personality and my identity that I split myself into seemed to almost take on the appearance and presence of separate individuals with minds of their own."
    h "Somewhere along the line, I was no longer playing a role, but was instead looking in a fractured mirror where each reflection seemed to have its own opinions and takes on different topics."
    h "I could bounce ideas off of each one, watch them talk to each other, and see them develop over time."
    h "Each one had their own ego with their own distinct idiosyncrasies."
    h "Sometimes, they would pick up habits and ideas from others and co-opt them, becoming similar, or growing."
    h "The interactions were soon taken out of the social networks and became more complex."
    h "Anything that people could do with each other, we did with one another: music, art, love, conflict, all of it."
    h "Music and art in particular were very interesting and followed a trajectory similar to our sense of humor."
    h "In the case of musical improvisation in a group, while we began with traditional instruments and sounds,..."
    h "once we realized that the limitations we had previously no longer applied, our sounds and melodies entered the realm of the otherworldly."
    scene bg trillions_of_possibilities4
    h "It is not simply a matter of playing the right notes."
    h "Eventually, it grows in complexity."
    h "Soon, it is quick repeatable patterns of key changes."
    h "Later, it became a matter of changing the instrument that plays a particular part in the middle of a bar."
    h "Nothing is off limits, which means that anything can happen regardless of whether it is physically possible or not."
    h "As long as it has a certain level of predictability, then it is still musical."
    h "If it can be followed, then it is music."
    h "This seems to be the nuance between sounds with musical qualities, and pure noise."
    h "One has recognizable patterns while the other does not."
    h "The pattern does not necessarily need to be easy to follow, but it needs to be there."
    h "That is the basic requirement."
    h "Outside of that, anything can happen."
    h "Replace your musical instruments with the whirs and hums of machinery, remove a part completely, use silence as a central part of your song."
    h "The structure of songs themselves can also be completely unconventional..."
    h "where they do not necessarily have a beginning or an end, but transition from one part to another in a loop like an auditory Möbius strip that ends where it begins and begins where it ends."
    h "Conversely, they can become inverted where melodies become the backing while the backing takes center stage."
    h "Some of these concepts have been tried in 21st century music, but others such as the infinite loop are not as conventional."
    h "Then there are the vocals."
    h "In this world, to overcome the limitations of the human voice, there is more than just autotune."
    h "Voices can be modulated and changed without limit."
    h "Sometimes, the human aspects can be merged with other instruments or the sounds of other animals to create something alien."
    h "Language too is without limitation."
    h "Instead of sticking to a single language, words from different parts of the globe as well as languages that never existed can be used to form sentences and verses regardless of grammatical coherence."
    h "For us, there is no need for language other than to organize our thoughts as one being, so language can take on a more abstract form to suit our artistic needs."
    h "A little bit of Mandarin here, some Arabic here, and let's sprinkle in some ancient Greek to spice things up."
    h "It doesn't matter if it makes sense."
    h "In fact that is better."
    h "The harder it is to make connections between the words, the more the listener has to work to make the music work for them."
    h "It is an exercise in self-gratification through forcing a certain level of imagination and creativity on the listener."
    h "Film is no exception either."
    h "In addition to the sequels, there are also original movie premises playing rent free in our head."
    h "Can you imagine that the Rocky franchise has made it all the way to 5000 sequels?"
    h "I can't either."
    h "At first, watching Rocky go back in time to box Hitler was thought to be the peak."
    h "However, soon we kept topping the previous entry until we hit 5000."
    h "There's something that never gets old about overcoming adversity to eventually triumph."
    h "I tried to hold a Rocky marathon, but somewhere along the line, I forgot the plot events for a large amount of them which shortened the marathon significantly."
    h "Rocky is no exception."
    h "George Lucas would be rolling in his grave if he saw what we did with Star Wars."
    h "Disney would likely be collecting trillions and quadrillions of royalties from other properties."
    h "All those oversaturated superhero movies just keep coming and coming regardless of whether they are good or bad."
    h "What is nice about the current creative environment is that we are no longer motivated by the box office, subscribers to a streaming service or a financial quarter, so anything is allowed."
    h "We can make every indie film and every indie film with too large of a budget."
    h "It all lives in our head, so there are no costs or liabilities borne in terms of special effects, computer graphics or stunt work."
    h "Some of the actors who form a part of me need some way to pass the time,..."
    h "so we can create works that not only have an unlimited budget with perfect visuals, but also add in the star power and recognition that the films of old had."
    h "It is the best of both worlds when we can keep a stable mind."
    h "There are those among us who saw this as an opportunity to create a virtual currency based on an economy of thoughts and ideas,..."
    h "but that was quickly shot down as idiotic and as a way to pointlessly impose limits on ourselves."
    h "When anything is possible, why introduce currencies and scarcity when it serves no purpose?"
    voice1 "Don’t ruin it."
    voice1 "We did enough of that before."
    h "In addition to the stars and celebrities that were alive at the time of the curse, there are the stars and celebrities that were born out here in space..."
    h "through the amalgamation of the best qualities of some of the more admirable individuals within the industry."
    h "Some of them were not even human."
    h "Finally, the dead have been brought back to life to cameo in the summer blockbusters."
    h "Imagine Marlon Brando or Laurence Olivier making powerful appearances on the scene and reminding everyone of what acting is."
    h "It is an everlasting golden age of ideas and creativity."
    h "The number of high quality items outputted varies from time to time, but it has its ups and downs."
    h "You never know when inspiration strikes, or when parts of you become too mentally exhausted to play along."
    h "The lulls in creative output have made it hard to pass the time, but it also allowed for a break in the frantic output in an attempt to forget about the situation we have been forced into."
    h "With the dying universe and our limited ability to observe the world around us, our reasoning and imagination has been strengthened tremendously."
    h "This has enabled us to effectively live in worlds of our own creation without a need to care about what is happening on the outside."
    h "The inside has become all that mattered and it is the mechanism by which we can live a semblance of a life."
    h "The many lives we have experienced have been countless and have taken place on planets, in space, in impossible locations, and in realities with their own unique rules."
    h "There have been realities with magic, fantastical places with superheroes..."
    h "and realities where we can live completely unencumbered by time, space, and any limitations other than the ones that accompany our mental processes."
    h "Imagination and thought have effectively been the tools that we used to seek solace from the chains that bound us in the real world."
    h "At times there are some nagging thoughts that can break the dream."
    voice1 "None of this is real."
    a_voice "We still suffer within our dreams."
    h "The human condition is one of ups and downs and as a result, we experience traumatic events within our dreams that remind us of painful times."
    h "At the same time, overexposure to happy moments and a continuous deluge of wish fulfillment have dulled our senses to the point that the ups no longer feel like the good times and seem more like business as normal."
    h "What is good is boring, and what is bad can stand out when you place your hands over your non-existent ears and try to close your non-existent eyes."
    h "The dreams that were the most painful were the ones that took place here in the present."
    h "Not in the past when we were humans and not in another world where we can escape, but here in our present where we are facing against a doomed future."
    h "The dreams that took place in our present that gave us hope or introduced change into an unchanging environment were the ones that made us feel something again."
    h "In one such episode where we were dreaming while awake, I imagined that one of those friends, those companions that traveled alongside me throughout the early part of my existence, came back."
    h "They came back all grown up and capable of understanding who we are."
    h "They came back, hardened by the pressures of this dying universe, and reached a point where nothing can threaten their existence anymore."
    h "While they could have left and never visited us again, they came back."
    h "They came back to this grotesque creature who could not speak or provide."
    h "They came back despite the challenge of doing so and with no expectation of payment or reward."
    h "They had no physical presence, but for our sake, they took on a form that allowed for us to see them as though they were another entity we could interact it."
    h "In our time of solitary confinement in the largest prison, they knocked on the bars to our cell in the form of a winged ball of light and said, \"Hello.\""
    h "The visions I had were of one of a great dialogue that lasted for thousands of years of greetings where we made each other's acquaintance and grew to know one another as different civilizations."
    h "It initially began as a series of signals, like a light based Morse code."
    h "This eventually changed to a number of tests where they streamed different types of particles towards us to see what effect it had."
    h "Eventually, they managed to transmit sound directly within our minds and we could communicate through a sort of telepathic means."
    h "At first, the conversations were crude as they gradually compiled a vocabulary and grammars and as we tried to adhere to a single language."
    h "What was originally a number of questions regarding names, time, and location eventually became more full-fledged conversations with more abstract details."
    h "They told us of their story and their beginnings as a civilization."
    h "They explained where their home planet was and the trajectory of their growth as a people."
    h "We learned that they were not just one species, but a coalition of many species that evolved from similar species on a planet located many lightyears away from where Earth once was."
    h "We told them of our history."
    h "How we grew and multiplied, how we left the pull of our planet, created artificial intelligence, and how we found ourselves like this."
    h "They attempted to explain to us the mechanisms of how they were able to establish communication while we tried to build upon our understanding of physics to reach some level of comprehension of what exactly we have become."
    h "Their descriptions of unconventional states of matter and nested loops of time would fly over our head."
    h "We discussed cultural similarities and how the way we think was dependent upon our physical states and the languages we use to describe our environment."
    h "There were times when nuances were lost, or when single words would have multiple meanings which resulted in ambiguities when discussing complex ideas."
    h "It is one thing to make a simple greeting in another language, it is another to have a fluid conversation, and it is another to discuss highly specialized topics within that language."
    h "These frustrations were gradually smoothed out over the years, but when such situations did appear,..."
    h "we found ourselves explaining simple concepts in a highly detailed manner, or reverting to using mathematics to find common ground."
    h "As math can be fairly unambiguous and precise, it was a good method by which to eliminate situations where clarity may be lacking."
    h "With that said, the act of using math as a medium by which to communicate certain things can be draining."
    h "While they have computational capabilities that are orders of magnitude more advanced than anything we have ever developed..."
    h "prior to the curse, we simply have a human level intelligence with the memories of billions of humans."
    h "When it came to such conversations, we were undoubtedly the bottleneck and I remember being quite grateful with how patient they were during such exchanges."
    h "It is not an understatement when I state that our technological achievements and the knowledge we gained over the years..."
    h "were nothing in the face of a civilization that managed to survive up to this point and freely travel through the universe as though they were taking a languid stroll through the countryside."
    h "We eventually arrived upon what was to become of us."
    h "We could simply vanish into the darkness."
    h "However, they told me that to do so would be a waste of an opportunity."
    h "They told us of a place where we could live."
    h "Not in another time or in another universe, but in this same universe."
    h "We were told that there were many faces to this reality, and what we knew was but a fragment of what was out there."
    h "We were supposedly just fish living within a glass of water that gradually gained cracks over time, and that there was an ocean out there."
    h "It was far away, but it was out there."
    h "There, we could live if we so pleased."
    h "We could have a place to call our own, a return to the individual identities and bodies we once had, and an appropriate amount of guidance to ensure that we do not repeat the mistakes of the past."
    h "The stories they told of these hidden parts of the universe were fantastical."
    h "There were monsters and giants out there of which they knew, and they believed that there were deities and gods surpassing even them in the spaces beyond which they have yet to comprehend."
    h " They told us of creatures that traveled from universe to universe, imparting wisdom to intelligent species or poaching them by introducing varying amounts of entropy into closed systems."
    h "They told us of battles being fought between conservationists and prospectors hoping to either preserve or exploit multidimensional reserves."
    h "There were battles and wars that transcended time, space, dimensions, probability, and even mathematics and common logic."
    h "These are metaphysical wars that are beyond the comprehension of our companion, but they have enough capacity to at least understand such battles were occurring."
    h "Within such a tapestry of interplay, we were to live within a small portion of a multiversal reserve that was being protected by the environmentalists on the outside of our three dimensional fishbowl."
    h "At the same time, they offered us three other choices."
    h "The first was to take us into the past and place us where we once stood."
    h "All the problems and luxuries we had would once more be ours to carry if we choose, and we would be able to live out the fate we would have lived if there had been no interference whatsoever."
    h "The second was to offer each and every one of us a life that suited our tastes."
    h "All of us would go on to live a life of our choosing in different parallel universes."
    h "It was a tempting offer."
    h "Finally, the third choice was to simply leave us alone to see our current state through to the end wherever or whenever it may be."
    h "They would simply leave, and nothing would happen."
    h "In the case of the first two, we were also given the option of keeping our memories of this ordeal we have spent the lifetime of the universe experiencing, or erasing them and reverting to zero."
    h "Each possibility had its appeal and its own set of disadvantages, some more than others."
    h "By the time we made a decision, the dream stopped."
    h "I don’t think any of us wanted to know what we chose, since doing so may reveal more of ourselves than we wished to know."
    h "In the case we did make a decision, knowing of the unchangeable aftermath may also be soul crushing."
    h "It is strange how despite being a species that desires change, we are also afraid of it."
    h "We only want to improve our situation, but rarely do we wish to take risks to that end which may also result in setbacks."
    h "Of course, there is always the risk of inaction which, while it may result from indecision, is a decision in and of itself."
    h "There was one other dream that I found deeply unsettling."
    h "It was one where we found ourselves face to face with the one who placed us in this situation."
    h "When given the chance to converse, to ask questions, to plead and beg, we stayed silent."
    h "Here was the one who holds our fate in its hands, and yet we are unable to do anything."
    h "It was not because we were incapable of action, of thought, or speech, but rather because we chose not to act."
    h "The being that made us this way chose to take on a form that we would understand and sense."
    h "It would place itself right in front of us, and wait."
    h "It does not ask anything of us or act."
    h "It just stays there, and in the face of inaction, we are unable to do anything."
    h "What happens to us is completely up to us, but we do not think a thought, demand an answer, throw an insult, or react in fear."
    h "We defined ourselves by what we did."
    h "Our accomplishments were the sum of our actions."
    h "However, in the time when it mattered the most, we did nothing, and the dream ended."
    h "In the place of those visions were nothing more than voices echoing back at us."
    h "They tell us of the mistakes we have made, the mistakes we are making, and the mistakes that we will make."
    h "All we can do in response is to simply dream another dream and hope for a satisfying ending."

    menu:
        "Try to flex phantom limb":
            jump P3C3
        "Do nothing":
            jump P3C3