# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

image bg empty_hospital_bed = "P3C3/bg P3C3 An empty hospital bed in a modern hospital.png"
image bg empty_hospital_bed2 = "P3C3/bg P3C3 An empty hospital bed in a modern hospital 2.png"
image bg empty_neonatal = "P3C3/bg P3C3 An empty neonatal section of a hospital.png"
image bg empty_neonatal2 = "P3C3/bg P3C3 An empty neonatal section of a hospital 2.png"
image bg forgotten_by_time = "P3C3/bg P3C3 Being forgotten by time in a photorealistic and surreal style.png"
image bg running_from_responsibility = "P3C3/bg P3C3 Running away from the responsibility of parenthood in a photorealistic and surreal style.png"
image bg running_from_responsibility2 = "P3C3/bg P3C3 Running away from the responsibility of parenthood in a photorealistic and surreal style 2.png"
image bg cycle_of_death = "P3C3/bg P3C3 The undending cycle of life and death in an ethreal and mindbending style.png"
image bg cycle_of_death2 = "P3C3/bg P3C3 The undending cycle of life and death in an ethreal and mindbending style 2.png"
image bg increasing_entropy = "P3C3/bg P3C3 The nature of the universe being one of increasing entropy.png"

label P3C3:
    scene bg empty_hospital_bed

    show screen centeredbox("{size=+10}Chapter 17: Steps Towards the Finish Line{/size}")
    pause
    hide screen centeredbox
    
    h "The birth was difficult."
    h "Before the predicted due date, her body was already weak and it was uncertain what medical complications might arise during the final days of the pregnancy."
    h "We think we can depend on modern medicine, but it is just a stop gap for the creeping fate that all of us have."
    h "This is assuming that proper treatment is provided which is not always the case when considering all of the bureaucratic hoops the average patient needs to jump through..."
    h "in addition to placing oneself at the mercy of human error."
    h "Childbirth is always traumatic to the body regardless of the level of health of the mother, and it leaves its mark and shortens the lifespan."
    scene bg empty_hospital_bed2
    h "Such is the price of creating another life."
    h "It is the price that accompanies carrying a child for nine months."
    h "It is a price that is paid in the form of effectively running the human body at a higher speed and under a higher load so that it can properly account for the life that it will eventually bring into the world."
    h "Heart rate, metabolism, blood pressure, hormones..."
    h "all are affected."
    h "In such conditions, one has to wonder what is prioritized by evolution: the life of the mother, or the life of the child?"
    h "One has the potential to produce more offspring and raise the offspring while the other is the future of the species."
    h "For some species, birth kills the mother while producing multiple offspring..."
    h "while for others, offspring are plentiful to the point where cannibalism is sometimes not only not counterproductive, but also encouraged depending on the situation."
    h "For us humans, however, the child seems to serve greater importance."
    scene bg empty_neonatal
    h "In a sense, the moment one's offspring is born, it becomes the beginning of the end."
    h "You as a person die, and in its place is a drone that serves the needs of the child."
    h "Your hopes and dreams become lowered in priority, and whatever you may have had planned are less valid."
    h "To intentionally have a child is very much an act of self-sacrifice as it is a shifting of priorities."
    h "You effectively push your hopes and dreams onto your child because time is running out for you."
    h "This, in a sense, is also a way of holding back one’s descendants."
    h "You missed your chance, so you leave everything to the next generation, sometimes forcing your ideals on your children to negative effect."
    h "It is something humans in every era have been guilty of."
    h "Your accomplishments are only relevant to the present and forcing them upon the next generation is proof of living in the past."
    h "It is as though an ape is telling a human to climb a tree instead of walking on two feet."
    h "It is as though a knight is admonishing an office worker for being unable to duel to the death."
    h "It is a form of generational procrastination where the previous generation imposes their will on the next while also diminishing their will in the present."
    scene bg empty_neonatal2
    h "Your child is a message in a bottle to the future."
    h "In the process, you not only give yourself for the sake of the child, but also acknowledge that you have become a lost cause."
    h "The future is no longer about you."
    h "Furthermore, the future that you are in the process of building is not one you will ever see or fully understand."
    h "That future has no place for you."
    h "You are old news, and if you raise your child well enough, you may be able to redeem yourself and your failures."
    h "You do this because your legacy is the only thing that we believe truly lasts."
    scene bg cycle_of_death
    h "The tree that dies is replaced by the forest it seeds."
    h "That is the idea."
    h "From your efforts, a lineage that will eventually make a dent will emerge and validate your efforts."
    h "Of course, the cycle never stops."
    h "Your children will attempt to succeed and by failing in doing so, they push their plans onto their children as well."
    scene bg cycle_of_death2
    h "Humanity is nothing more than a series of failures where any sense of progress is truly gained by learning from the past."
    h "When the mistakes of the past no longer apply, new types of challenges and the respective failures that originate from them make an appearance."
    h "It is not simply that we are always failing, but rather that we are usually failing at different things."
    h "The first steps were a memorable moment."
    h "It was definitely strange to see a creature completely incapable of caring for itself move with autonomy and intention."
    h "Stubby limbs and uncoordinated movements eventually result in the convergence of controlled actions."
    h "The very idea was a paradox."
    h "These first steps were not only an exercise in moving the body, but to move it with a certain level of confidence and conviction."
    h "The act of walking is difficult for robots to replicate, but this child could do it so effortlessly and only improved over time."
    h "Although we take this for granted, the act of walking and navigating through a space is actually complex."
    h "Walking is something we do every day, but for our child, the first time was a milestone for hundreds of millions of steps to follow."
    h "This is the beginning of a journey that starts at a road that extends far beyond the horizon."
    h "From the perspective of a parent, it was an exciting moment, but also one of concern, because the ability to move forward could be a double edged sword."
    h "On one hand, the only way we progress is by putting one step in front of the other by moving in an incremental manner."
    h "Conversely, if you are not looking, you could easily walk your way off a cliff simply because you are unaware of what to watch out for."
    scene bg running_from_responsibility
    h "I suppose that is where my responsibilities lie: to ensure that our future progresses in the right direction."
    h "What is the right direction?"
    h "No one knows."
    h "If you are an incompetent parent, the right direction is simply any direction away from you."
    h "It is any direction that can reduce your responsibility and workload."
    h "How I wish I could run away from this responsibility without any regrets."
    h "However, my obligations seem to guilt me into staying where I am despite it not necessarily being in my best interests."
    h "I hope I am not an incompetent parent, but I cannot predict the future."
    h "A family is a relationship of mutual trust."
    h "Whether that trust becomes broken or not requires the cooperation of all parties."
    h "I hope that this child will grow in a stable household and I will act in a manner to ensure that that becomes a reality."
    h "However, I am well aware that effort is merely a prerequisite for results."
    h "At the end of the day, luck and outside conditions play a significant role."
    h "Of course, at some point, this child will need some form of independence and a family is just a foundation that acts as bedrock to take flight from."
    h "I hope that he will be able to realize that although life can be carried out alone, to be human requires participation in society and interaction with others from the day of birth."
    h "Although I hope our descendants can transcend society, our biology prevents us from doing so."
    h "When the time comes, will he be able to make friends?"
    h "Will our child have the capabilities needed to find allies in the many wars each and every one of us inevitably fights so as to live and live well?"
    h "In the battle against time and expedition to progress through life, will he be able to navigate the challenges and claim victory?"
    h "All we can do is simply provide our children with the tools needed to handle the world."
    h "Whether they use them or not and how they use those tools, skills, and experiences is ultimately within their hands."
    scene bg running_from_responsibility2
    h "The responsibility that weighs us down as parents early in a child's growth can weigh us down even later in life when we have little control."
    h "The guilt and obligation can act as a curse or a burden even though it does not feel wrong to wish to have some level of influence on factors we ultimately have no rights to control."
    h "Our child too is an individual with their own thoughts and emotions."
    h "As parents, what we can do is be there and guide them."
    h "As we consider the future, our own thoughts about our relationships become uncertain."
    h "We do not know what will happen to us."
    h "Will we be there to watch this child grow?"
    h "To have such a privilege cannot be taken for granted."
    h "Similarly, we do not know if these relationships will always exist."
    h "Will we fight?"
    h "What will we fight over?"
    h "Will it be something trivial that ends it all, or will it be a number of mistakes and failures cascading until something gives and breaks the camel's back?"
    h "Yes, relationships do not last forever."
    h "However, they are best when they are positive."
    h "The nature of the universe is one of increasing entropy."
    h "To maintain order, energy is required to keep the forces of chaos at bay."
    h "I do not wish for us to become estranged."
    h "I do not wish to grow old while they never think of me."
    h "I do not want to be hated for years on end while constantly thinking of how I can gain forgiveness."
    h "That is a life I do not want to live."
    h "I do not want to live without a family."
    h "I do not want to live without people I can trust."
    h "In my old age, will they be there for me?"
    h "Will they care for me when I can no longer care for myself?"
    h "I can envision myself at the end of all of this dying alone as I know many others have."
    h "I can see the same fate befall my spouse, our child, his children, and many others."
    scene bg forgotten_by_time
    h "I can see the earth rotting to dust long and combusting within the sun after our graves have been defiled by nature and there is nothing to remember us by."
    h "I can see us being remembered by our children and perhaps grandchildren and then being forgotten by our descendants afterwards with nothing more than a gravestone to stand as some proof that we have lived."
    h "I can see the same happening to our children as well."
    h "Unless you are a great leader, a conqueror, a mass murderer, or an influential thinker, you simply do not matter."
    h "Those closest to you will be the last ones to remember you, and as time passes, you will be lost to the sands of time."
    h "No one will remember you."
    h "No one will know you existed."
    h "You will have died never leaving a mark, and even if you did, you will be outshined by those who came before you and left a larger mark."
    h "Even they will no longer matter when the last human dies, when our culture vanishes, and when the earth turns to ash."
    h "Nothing is permanent including you and the marks you and your descendants tried to leave."

    menu:
        "Try to flex phantom limb":
            jump P3C4
        "Do nothing":
            jump P3C4