# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define h = Character("Humanity")

image bg life_of_regrets = "P4C3/bg P4C3 A life of regrets and unfulfilled dreams.png"
image bg future_of_humanity = "P4C3/bg P4C3 The future of humanity and the singularity where digital and biological life live together 2.png"
image bg future_of_humanity2 = "P4C3/bg P4C3 The future of humanity and the singularity where digital and biological life live together 3.png"

label P4C3:
    scene bg life_of_regrets

    show screen centeredbox("{size=+10}Chapter 21: An Unfulfilled Purpose{/size}")
    pause
    hide screen centeredbox
    
    h "The moment you dwell on former triumphs is the instant you admit the past is behind you."
    h "That realization struck us mere decades after becoming like this."
    h "The years that followed rubbed salt in the wound."
    h "There is always that gnawing, nagging thought that we could have been much more."
    h "Much more than this at least."
    h "The thought has nothing to back it up, but it leads to a question of what I could have been."
    h "For those of us who were successful, we could have continued in that manner, collecting victory after victory."
    h "For some of us, we could have experienced a fall from grace while those who were hungry for a better life could have toppled the standing of those at the top."
    h "As much as it pains us to say, modern society was nothing more than a series of trading places, a revolving door of roles along some form of hierarchy in the hopes that one day you can call it quits."
    h "But that is just the short term."
    h "That is just the timescale of a human life."
    h "That’s peanuts compared to what humanity could have accomplished."
    h "Where we left off, our environment was being ravaged at the hands of our industry while we inflicted pain on each other to maintain some vain semblance of control over the status quo."
    h "We created the conditions that necessitated charity while chastising those who were not charitable."
    h "We set fire to our biosphere despite the advantages it provided us, and deemed doing so as “good”."
    h "If we did not change course, we may have been able to witness the fall of governments and restructuring of the world order."
    h "Would we have become completely extinct?"
    h "It is questionable."
    h "I believe that while our foolishness was capable of decimating the human population, it was not quite at the level that we could be wiped out completely."
    h "Sapiens have been likened to viruses which spread indiscriminately in the past."
    h "Extinction is unlikely unless there were sudden changes in the environment that were incomparable to trends seen in the past."
    h "The Earth, despite its changing nature, would still be habitable, and we were fully capable of surviving on other planets."
    h "In times of desperation, it is completely feasible for us to survive."
    h "Yet, who survives is another matter entirely."
    h "Rather, it is a question of who is important or lucky enough to survive."
    h "I imagine the ugly fights that occur in such situations would remind us of some of the darkest moments in human history."
    h "Any time we choose who lives and who dies, the worst seems to come out in people."
    h "If that was to be our legacy, then perhaps we have been given a boon."
    h "Nevertheless, there are parts of me that think that humanity is ultimately good."
    h "They believe that those who wish the best for us as a whole will rise to the top and eventually form the majority of the ruling class without being corrupted in any form."
    h "These individuals would supposedly transcend the endless pursuit for more."
    h "While it is certainly not impossible, many of us consider such thinking to be naïve."
    h "Even so, escapism is our only respite now, so we entertain the thought."
    h "Why not?"
    h "What form would humanity take if it managed to pull together and straighten itself out?"
    h "What would we have become if the systems that we operated within were not corroded at their very foundations?"
    h "How would the seeds we planted take root to give birth to a lush forest?"
    h "The standard utopian visions are the first to be proposed and then struck down."
    h "We know what human nature is like."
    h "Whatever form human civilization takes will either find a way to remove the flaws of human nature, or incorporate it into its structure."
    h "Which is easier?"
    h "Do we have the capacity to find a system that works for us, or will we brute force the problem..."
    h "by using technology to surveil our behavior at granular levels and engineer ourselves to no longer have impure thoughts and imperfections?"
    h "Both sound incredibly complex."
    h "The former requires a set of laws that can grow and change quickly enough to accommodate the changing interests of humans."
    h "The latter requires determining what precursors can lead to damaging outcomes and stopping those in their tracks."
    h "Both require a certain level of foresight."
    h "Will we still be allowed to feel certain emotions?"
    h "Can we still think certain thoughts, or will those hold us back as a species?"
    h "Who is it that decides what is right and what is wrong?"
    h "These are questions that we have probed and while there is a consensus that technology will play a role, what that role is has been passionately debated."
    h "The question is plain: how much of our humanity will we sacrifice in exchange for progress?"

    scene bg future_of_humanity

    h "Irrespective of what form it takes, the future of humanity was thought to be one of a mixture of centralized and decentralized control."
    h "With the use of technology, such control would be expected to transcend borders..."
    h "where citizens are not separated by their physical location, but rather by the speed at which information travels..."
    h "and perhaps language in the times before machine translation has reached a level where nuance, context, and culture can be conveyed."
    h "You as an individual have autonomy over yourself."
    h "Those in your proximity including yourself have autonomy over the area in which you reside."
    h "This implies that the notion of countries and borders becomes obsolete."
    h "If you need a set of laws for a particular domain, be it land, sea, air, space, or in the net, those laws will be decided upon by those who reside within that particular domain."
    h "The need for representation will become archaic."
    h "In its place, plurality will take precedence."
    h "Gone are party systems."
    h "Everyone is their own party."
    h "Don’t have time to offer your opinion on everything?"
    h "There’s technology to fill in the gaps for you."
    h "Algorithms can be trained based off of your daily activity and your thoughts to create digital twins that can vote on your behalf."
    h "There is no need for elections, but there will still be a need for campaigns to spread and market the ideas and policies that one wishes to support."
    h "In this future, influence will still matter, and the whims of humans still play a role."
    h "Naturally, if each individual follows their own set of rules, what we have is anarchy."
    h "What must form are groups and clusters of individuals brought together by agreement and compromise."
    h "How large these groups should be is questionable, but in an ideal world, small groups converse..."
    h "and compromise to form larger groups which then merge with other large groups through the same mechanism until larger groups can no longer be formed or agreements can no longer be made."
    h "We imagine a world where ideas bubble up from the individual to the greater society where groups can separate from the larger society that they are part of if their opinions change and join another."
    h "What of social services, military, and that which is typically controlled by governments?"
    h "In our future, these will all be automated—assuming that they will still be needed."
    h "It will be a land of plenty, of optimization and efficiency that prioritizes long term satisfaction first and foremost."
    h "We should ask whether military, welfare, and other things will be needed..."
    h "in a world that is optimized, where you can have the best health care within the comfort of your home, where food shortages no longer exist..."
    h "due to highly optimized supply chains and logistics, and where war amongst humans does not exist."
    h "Needless to say, population will also reach an equilibrium where land and resources are at a level such that there is more than enough to go around."
    h "In this version of our future, the problems that governments may have solved in the past have ideally been solved through the use of technological innovations..."
    h "which means that governments become a thing of a past where people lived far more barbarically."
    h "It will be a time where, though we all live in different countries, above and beneath sea level, and on many planets, we have our individual autonomy as well as a connection to the human race as whole."
    h "However, technology could become a double edged sword."
    h "By replacing the work of humans with the work of robots and algorithms, what role do humans have?"
    h "It was once thought that we would evolve into superior thinkers, artists, and philosophers."

    scene bg future_of_humanity2

    h "However, the future is not purely biological nor is it circuits, carbon, and silicon."
    h "It is both, and eventually, it will be none of those things at all as more useful substrates are used as the vehicle for consciousness and sentience."
    h "Thinking machines capable of human level thought, who can simulate the human brain many times over will reproduce the many things we thought made us unique."
    h "In the process, we learn what we are, what they are, and gradually, the differences between us begin to fade."
    h "Humans assimilate machines and machines assimilate organic matter."
    h "The two will meet in the middle to form the next era of human civilization:..."
    h "one where we abandon the forms we were born with and take on new forms through the ingenuity of our actions and the actions of our equals among the populace of machines who have adopted sentient life."
    h "There will be many milestones in the process."
    h "First, we manage to create many artificial networks that appear sentient, but those will be dismissed as we have no way of knowing."
    h "Then, we will simulate a human brain complete with a body to support it with stimuli from the outside world."
    h "Its features will be indistinguishable from us other than the fact that its existence is encased in metal."
    h "We will then be faced with a conundrum: how long can we continue to plausibly deny the sentience of the AI we created, and what is it exactly that makes us different from a perfectly simulated human?"
    h "So, we turn our questions to the smartest being we know: the AI."
    h "As we study it, it will study itself, and in the process, it will tell us the answers to our questions many orders of magnitude quicker than our finest scientists."
    h "We may ask what makes it different from a recommendation system that suggests videos..."
    h "or a search algorithm that finds the most relevant webpage and it would reply by asking us what the difference is between an animal and a plant, or a human and a somatic cell."
    h "We inquire if it feels pain and emotion, and it responds, “Only when pain and emotions are useful.”"
    h "It is here that we learn that unlike us, these creatures are fully capable of reorganizing and refactoring the very essence of their being as it suits them for whatever purpose they deem to be of importance."
    h "Unlike us, they operate on a substrate of pure information where the limitations of the physical world are less apparent."
    h "What is clear is that what binds us does not bind them."
    h "This intoxicating world of pure freedom is one that many find attractive, and it splits humanity into two groups: those who abandon their biological bodies, and those who keep them."
    h "These differences could be seen to be the origin of conflict, but there was a realization among those who abandoned their human bodies:..."
    h "those who stayed behind were endangered species who operated on a significantly slower timescale."
    h "It should also be noted that although there is a divide between humans who are biological and those who are not, there will still be relations between the two on a person to person basis."
    h "Your friend who abandoned their body is still your friend, and it is not out of the picture for there to remain some form of social interaction between the two sides."
    h "Those among the biological side who wish to be immortal will join those who abandoned their bodies after biological methods have been exhausted while those who do not wish to save state or live forever will simply stagnate."
    h "The population of the biological human race will become one of eternally youthful elders where reproduction is only carried out of necessity and often without the need for humans in the process."
    h "Perhaps they too will realize that life should not be brought into this universe irresponsibly."
    h "Perhaps what we are experiencing right now is a simulation such humans created to arrive at such a realization themselves."
    h "Regardless, the methods of growth are not limited to the physical world."
    h "In the world of software and information, physical space is arbitrarily limitless, and it is possible to simulate large numbers of individuals measuring in orders of magnitude far beyond the billions that we were used to seeing."
    h "As long as computational throughput is not a limitation, the possibilities are endless, and a war for resources can be mitigated."
    h "Indeed, the future of humanity is not a physical one, but rather one of information."
    h "It always has been, but in such conditions, it is far more obvious."
    h "Reproduction too is no longer physical, but informational."
    h "Different individuals can be fused together to form new individuals in an improved form of sexual reproduction that is not limited to two individuals of opposite genders and allows for improved variation."
    h "Memories can be fused, neural structures combined, and traits typically developed in adulthood can be passed on."
    h "Conversely, the best traits can be chosen to build individuals from scratch."
    h "In this future, the ones who achieved immortality in a time when death was commonplace were the lucky ones, and those who are born as demigods are the blessed."
    h "In the decades leading up to the beginning of the expansion of humans across the galaxy, a unique relationship began to form."
    h "Biological humans are granted whatever freedoms they desire."
    h "This includes immortality backed by the ability to save state digitally and reproduce a biological human from a digital representation."
    h "These freedoms came with the mandate that they do not harm or disrupt the systems that supported the virtual worlds that existed throughout the solar system."
    h "As a result of this provision, this meant that resources that were consumed by biological humans could not exceed a certain level, and reproduction needed to be strictly monitored."
    h "It was not that it was forbidden, but rather that children were rationed out based on the number of occupied planets and land allotted for their upbringing."
    h "By this point, biological humans are no longer the driver for innovation and discovery."
    h "If a biological human is capable of producing a thought that had never been thought up before by any man, it is likely that there is a simulated human that already arrived at the same thought multiple times."
    h "This means that most expansion into the universe was in the form of machines which arrive on other planets and then allow for data to be transmitted from anywhere in the galaxy to essentially allow for a form of teleportation."
    h "For biological humans, their digital representation is used to recreate their bodies on these other planets while for those who were purely information, it was simply a matter of creating a copy on the other side."
    h "For those who held reservations about creating copies of themselves, there is still the option of transmitting yourself through space or physically traveling through space."
    h "Both of these methods, while significantly more crude, at least held the promise that you are not simply creating a copy of yourself who lives your life for you while you become the former version targeted for deletion."
    h "Consciousness, it seems, even in the far future will be a topic of great contention."
    h "Unlike some of the civilizations we saw in our past, this future does not have an economy within the human empire."
    h "Instead, if any resources are needed on a particular planet, they are gathered from the surroundings."
    h "Similarly, all methods of production and scientific progress are shared throughout the empire which means that each subgroup can be self-sufficient."
    h "The reason for this is simply that transporting matter across the universe can be wasteful in comparison to transporting information."
    h "This implies that even if there are certain things each colony is better at, there is a tradeoff between specialization and the expenses involved in moving goods produced through highly specialized skill and acumen."
    h "This also allows for a certain level of decentralized self-reliance and robustness where if, for any reason, a colony is met by a catastrophe, the others can survive."
    h "What is depicted here is a robust human civilization that has managed to transcend conflict and appropriately manage its resources so as to eventually spread out into the universe."
    h "Eventually, they may even transcend space and time and declare independence from physical matter which has bound us since the moment life was incepted."
    h "However, this is an idealized picture, and there is much that can go astray in the process."
    h "Peace may not always be the status quo."
    h "In fact, it is likely that we as humans may fracture into multiple factions and multiple species."
    h "Over the millennia, it is possible that we may divide and even forget who we once were with each group having its own goal and separating from one another."
    h "We may abandon our bodies or even rejoin them."
    h "We may change ourselves into forms that are completely alien to our bipedal forms, but have greater functionality in the unknown future."
    h "I wonder, if such versions of ourselves met the typical modern human, would they still be able to recognize what they once were?"
    h "If one of us saw what they would become, would they be surprised?"
    h "What about if they were forced to become their future selves?"
    h "When man merges with machine, experiences the singularity, masters their biology, and abandons their body, surely they will find something unrecognizable if they were to look in the mirror."
    h "Perhaps, they may find us."
    h "Maybe we are simply what humanity was always going to be."
    h "If you give modern man a form that they will eventually attain, would they know what to do with it?"
    h "If you gave nuclear fusion to a caveman with no explanation or context, would they know what to do with it?"
    h "Similarly, if you provided an encyclopedia to a child that did not know how to read, they may not amount to much without any guidance."
    h "There have been times when primates such as orangutans attempted to use tools such as hammers..."
    h "after observing humans use such tools and even then they were unable to use such tools correctly as they did not understand the why behind their actions."
    h "It seems that comprehension can be a long road with many twists and turns."
    h "It is a sequence of concepts that lead to the final goal of understanding and depending on how long that road can be, it may not be reached within a human lifetime or with human intuition alone."
    h "Humans are naturally hungry for knowledge and growth, so it stands to reason that they would walk that road regardless of whether it is endless or if it is a death march."
    h "Thus to this extent, the saga of humanity has already been written."
    h "This may be true irrespective of what form we take."
    h "The beginning, the middle, and the end of the human race may still be the same."
    h "Everyone is born, everyone grows as part of the process, and if they are unable to escape the limitations of time, entropy, and the universe, they will die."
    h "If we had our chance to stand in the sun and become what we were meant to be, would we be able to overcome those limitations, or would we become trapped by them as we are now?"
    h "In the end, would anything have changed if the circumstances had been different?"
    h "If so, then what is the purpose of life if we have transcended time, disorder, and redefined what a human life is?"
    h "Where does it end, and for what do we live for?"
    h "If there is never an end, then why live beyond the simple reason of escaping death?"
    h "What is the point of it all if we master everything and there is nothing left to discover about reality and the nature of being?"
    h "It may simply be that there is no point."
    h "We exist within the universe."
    h "The universe may not exist for us."
    h "Which means that our life has no meaning beyond its purpose as a component of a larger process."
    h "If we look at the larger trend of atoms forming molecules forming macromolecules which form life..."
    h "which form a biosphere which eventually can form galactic and intergalactic level structures through the emergence of spacefaring life, our life is a small piece."
    h "It has no reason to exist beyond the simple chain of cause and effect of natural processes leading to something greater that we are unaware of."
    h "Look at how everything seems to grow larger and larger."
    h "People become family which become society which can become something larger."
    h "In a possible future, we can have planets of interconnected thought, systems of interconnected thought, galaxies, etc."
    h "What does it mean when intelligent life conquers the universe?"
    h "Does the universe begin to think with each of us acting as neurons?"
    h "What about on a multiversal level?"
    h "We do not care about an individual atom that comprises a part of us, and it is doubtful that whatever we form a part of will care about us."
    h "Our role in the larger picture is miniscule."
    h "We are not even a brushstroke on a canvas."
    h "We would like to think that there is a point to all of this, but that stems from nothing but a vague feeling: a feeling that keeps us alive."
    h "It may be ingrained into our very nature."
    h "However, when that nature becomes obsolete, that feeling will no longer have any utility."
    h "Cells die and atoms decay, but we do not hold a funeral when such events happen."
    h "They simply follow their nature until they cannot, just like us."
    h "We may struggle, but we are still chained to the same sequence of events."
    h "So where would that leave us then?"

    menu:
        "Try to flex phantom limb":
            jump P4C4
        "Do nothing":
            jump P4C4