# The script of the game goes in this file.

# Declare characters used by this game. The color argument colorizes the
# name of the character.

define h = Character("Humanity")

image bg floating_in_endless_space = "P4C4/bg P4C4 Floating in endless space in a surreal style.png"
image bg floating_in_endless_space2 = "P4C4/bg P4C4 Floating in endless space in a surreal style 2.png"
image bg floating_on_ocean = "P4C4/bg P4C4 Floating on an endless ocean in a surreal style.png"
image bg standing_on_cliff = "P4C4/bg P4C4 Standing at the edge of a cliff in a surreal style.png"
image bg absence_of_purpose = "P4C4/bg P4C4 The absence of a purpose in a surreal style.png"

label P4C4:
    show screen centeredbox("{size=+10}Chapter 22: Meaning{/size}")
    pause
    hide screen centeredbox
    
    h "Our existence is devoid of an inherent purpose."
    h "It lacks reason."
    h "Now, before, and in the future."
    h "It will always lack purpose, because purpose and meaning are human creations."
    h "They are things we used to make sense of the world around us."
    h "They are simply inventions."
    h "Without them, we do not have context, and we cannot build upon a foundation of understanding."
    h "Each item and each thing has to have a meaning."
    h "If it does not, we would be unable to communicate."
    h "Meaning must also be static."
    h "If the meaning of something changes too often, it can become meaningless, because a term can refer to many different things."
    h "A world of changing meaning, particularly when such change is constantly occurring, would be hell for a human intellect."
    h "The mind would lose its footing and become disoriented like a schizophrenic losing their grasp on reality."
    h "For something to have a meaning, there is an assumption that it does not change significantly over time."
    h "Whether that something does change or not seems to be beyond a human’s ability to comprehend."
    h "Meaning, in other words, is temporally fixed."
    h "If something’s meaning changes over time, then that something is treated as a different thing."
    h "In a sense, it is the standardization of everything using discrete means."
    h "It is a way to categorize and file any object, concept, or thought."
    h "It is the “what” of the nature of existence."
    h "It is not the why."
    h "However, the “what” is purely multiple approximations of our reality, and it can be changed based on sentiment, opinion, and perception."
    h "If this thing that we base the foundations of our thoughts and reasoning on is so arbitrary, then figuring out the “why”, and “how” become a more arduous task."
    h "This is meaning in the strictest sense of the word, but when it is used to imply purpose and reason, then it becomes a matter of “why” which is a harder question to answer."
    h "Cause and effect can be more straightforward as it is simply a matter of determining the chain of causality."
    h "Granted, if we were ever to break free of the limits of time, then that would upend the why as we would introduce causal chains that are circular or even reversed."
    h "Nevertheless, when we ask what the purpose of human existence is, we are not asking about the logical chain of events that led to our existence."
    h "Rather, we are looking for something else."
    h "This “something” is not meant to provide us with a definitive answer, because there is no single answer."
    h "Instead, it is something that differs for each person based on their past experiences and desires for the future."
    h "It can be guided by emotion instead of logic."
    h "It is something that is born out of the finite nature of a human life to justify our existence as more than just chemical processes."
    h "\"This life has to mean something.\""
    h "\"Why would I continue with it otherwise?\""
    h "However, from an empirical standpoint, there is no such thing as a life’s purpose."
    h "It is a philosophical concept that was invented for us to continue living and to live in a deliberate manner."
    h "The reason for this being that we believe our life has value, and that value is maximized for the duration we are alive and minimized in the duration that we are not—particularly before we are born."
    h "This is why life necessitates a purpose regardless of whether or not there is such a thing supported by our existence."
    h "Even if there was, it is limited to a human life on a conscious level."
    h "So what is it for me?"
    h "What purpose would I, who is incapable of acting on the world around me and creating a legacy or descendants, who is a fusion of all human experiences but an individual in their own right, have?"
    h "I question whether it even matters and yet, it tears me up inside."
    h "I know that my problems in the past have all been solved by letting go, but there has always been a feeling that I was destined for something greater."
    h "This will never be."
    h "We, right now, represent both the peak and the trough."
    h "I wish at times that we had never evolved to the point that we were able to contemplate our own lives."
    h "A life of scrounging and survival to keep us busy would have been enough."
    h "Yet, it was our intellect that allowed for our growth as a species which meant that in the end, we were cursed to continue to grow more intelligent as long as such traits allowed for our continuation as a species."
    h "I wonder if there is a possible alternate reality where after securing our future and reaching a point where survival was trivial, we would choose to live in a state in which we have an intellect incapable of such thoughts."
    h "Rather than choosing between a biological and informational existence, we would choose one of a self-imposed intellectual diminishing."
    h "Would that be the easiest path to happiness?"
    h "To lobotomize ourselves and live in peace in a state where the challenges that the world posed for us have been eliminated?"
    h "Is that the final goal, or would we be too reluctant to give up an intellect that allows us the greatest of freedoms while rotting our mental health with the passage of time?"
    h "Our predicament may stem from the ambiguity in the nature of our identity."
    h "To begin, we are not our identity."
    h "Our identity is something we have, and it is formed by our past experiences."
    h "It is something that is within our control if we choose for it to be."
    h "It does not help that our past is like a dream that we are experiencing in a simulated manner through reminiscence."
    h "If the past actually happened and we experienced it, then we will never experience it again in the same way if the arrow of time points forward."
    h "If I as a sentient being have an identity formed by the experiences of all humans, what exactly is my identity if it is not an artificially fused synthetic amalgamation of the different people who I once was?"
    h "In this case, the predicament not only becomes one of finding my identity, but also determining who I am among the billions of voices that compose the many parts of me."
    h "It is true that the task of settling on an identity would have been easier if there were fewer memories and fewer pasts to draw from."
    h "Conversely, I can discard or ignore the pasts I do not like which means that my identity is free to be whatever it is."
    h "If I do so, would I still be me?"
    h "Like the ship of Theseus, if you take a ship and replace all of its parts is it still the same ship?"
    h "Frankly, I am losing the patience to even humor the discussion."
    h "This brings us to question why it matters who I am."
    h "Why do I need to have an identity?"
    h "Or even a purpose?"
    h "Why can I not just be?"
    h "There is only one of me."
    h "Who I am, and who I am to other people is irrelevant now."
    h "I can selectively forget that which I do not wish to remember and focus on only that which brings me joy."
    h "In a sense, as an individual, and as an amalgamation, it does not matter how many pasts I have if I can choose my past."
    h "In the end, the past does not change, and I can only choose how I am affected by it."
    h "This was true before and it is true now."
    h "Past, ultimately, does not matter."
    h "In fact, time does not matter."
    h "While it does not matter in an unchanging reality, it did not matter before either."
    h "The past can be whatever I wish for it to be despite it being set in stone based on how I choose to remember it."
    h "The present can be contextualized based on how I choose to think of it."
    h "The future has yet to occur and as a result, none of it exists."
    h "Once it becomes the present, I can simply decide how I wish to respond to it."
    h "It is irrelevant whether this emptiness is real or if I have been dreaming it all this time."
    h "Reality is just a foundation by which I can interpret to choose how to live."
    h "That is all."
    h "Perception is what matters, and we have full control of that."
    h "..."
    h "My life has had many regrets."
    h "I was never able to determine what our destiny was."
    h "I was never able to create a legacy that lasted infinitely."
    h "I learned many lessons too late, and I could never determine how I could impress my will upon reality."
    h "While I was allowed the privilege of witnessing the life of the universe, I wish I could have seen the beginning."
    h "The story that I can tell is a partial one."
    h "It is incomplete, and I wish I could have been allowed the opportunity to see the whole thing."
    h "If the universe has a beginning and slowly dwindles into chaos and nothing, then this story will end quietly and unimpressively."
    h "However, if the universe were cyclic, then there will be a day when I can see the beginning."
    h "I hope I can stay sane and live long enough to witness that."
    h "As passage of time brings upon a sickness the mind that gradually decays my existence, I wish it can at least end in a dignified manner with some answers."
    h "To end life with nothing but questions would lack resolution."
    h "Are we not entitled to at least that?"
    h "Or is that entitlement itself another thing we made up to comfort ourselves?"
    h "Any firm mental foothold that was once there within us has broken away beneath us."
    h "Now, all that is left is for us to fall into the abyss."

    menu:
        "Try to flex phantom limb":
            jump P4C5
        "Do nothing":
            jump P4C5